/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/config/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface-container": "#191a1a",
        "on-tertiary-fixed-variant": "#272993",
        "surface-tint": "#ff87b9",
        "tertiary-container": "#898efa",
        "surface-container-lowest": "#000000",
        "on-primary-fixed": "#000000",
        "error-container": "#a70138",
        "background": "#0e0e0e",
        "surface-dim": "#0e0e0e",
        "on-surface-variant": "#adaaaa",
        "on-error-container": "#ffb2b9",
        "primary-fixed-dim": "#ff4da5",
        "primary": "#ff87b9",
        "surface-container-high": "#1f2020",
        "on-tertiary-container": "#e8d0ff",
        "secondary": "#b884ff",
        "primary-fixed": "#ff6daf",
        "on-surface": "#ffffff",
        "inverse-on-surface": "#565555",
        "tertiary-fixed": "#a6a9ff",
        "inverse-surface": "#fcf9f8",
        "outline": "#767575",
        "error": "#ff6e84",
        "success": "#86d995",
        "warning": "#ffb86b",
        "on-primary-container": "#4b002a",
        "on-primary-fixed-variant": "#5c0034",
        "surface-bright": "#2c2c2c",
        "surface-container-low": "#131313",
        "on-secondary-fixed": "#4a0090",
        "inverse-primary": "#b9006f",
        "on-secondary": "#2f0060",
        "on-background": "#ffffff",
        "surface-container-highest": "#262626",
        "surface-variant": "#262626",
        "secondary-fixed-dim": "#d6b6ff",
        "tertiary": "#999dff",
        "on-tertiary-fixed": "#030062",
        "secondary-fixed": "#e1c7ff",
        "tertiary-fixed-dim": "#959aff",
        "secondary-container": "#6e06d0",
        "on-error": "#490013",
        "on-secondary-container": "#ebd8ff",
        "outline-variant": "#484848",
        "surface": "#0e0e0e",
        "on-secondary-fixed-variant": "#6f08d0",
        "on-primary": "#600037",
        "primary-container": "#ff6daf",
        "on-tertiary": "#110f82",
        // Chain Colors (Synced to Nocturne)
        "chain-base": "#0052FF",
        "chain-arbitrum": "#b884ff",
        "chain-mainnet": "#ff87b9",
        "chain-sonic": "#00e5ff",
        "chain-hyperliquid": "#999dff",
      },
      fontFamily: {
        'headline': ['Inter', 'system-ui', 'sans-serif'],
        'body': ['Inter', 'system-ui', 'sans-serif'],
        'label': ['Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        'DEFAULT': '0.5rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px',
      },
      animation: {
        'fade-in': 'fadeIn 0.2s ease-out',
        'slide-in': 'slideIn 0.2s ease-out',
      },
      backgroundImage: {
        'brand-gradient': 'linear-gradient(90deg, #ff4da5 0%, #b884ff 100%)',
      },
      boxShadow: {
        'neon': '0 0 15px rgba(255, 73, 164, 0.3), 0 0 30px rgba(184, 132, 255, 0.2)',
        'neon-strong': '0 0 20px rgba(255, 73, 164, 0.5), 0 0 40px rgba(184, 132, 255, 0.3)',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideIn: {
          '0%': { opacity: '0', transform: 'translateY(-20px) scale(0.95)' },
          '100%': { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
      },
    },
  },
  plugins: [
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    require('@tailwindcss/typography'),
  ],
}
