/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/config/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        // Design System Direct Variables & Tint Utilities
        bg: 'var(--bg)',
        surface: 'var(--bg)', // Preserves page background behavior for legacy bg-surface
        'console-surface': 'var(--surface)',
        surface2: 'var(--surface2)',
        surface3: 'var(--surface3)',
        field: 'var(--field)',
        line: 'var(--line)',
        line2: 'var(--line2)',
        fg: 'var(--fg)',
        fg2: 'var(--fg2)',
        fg3: 'var(--fg3)',
        'brand-pink': 'var(--pink)',
        'brand-violet': 'var(--violet)',
        ok: 'var(--ok)',
        warn: 'var(--warn)',
        crit: 'var(--crit)',
        info: 'var(--info)',
        'ok-bg': 'var(--okBg)',
        'warn-bg': 'var(--warnBg)',
        'crit-bg': 'var(--critBg)',
        'pink-bg': 'var(--pinkBg)',
        'info-bg': 'var(--infoBg)',
        tint: 'var(--tint)',
        'pink-hi': 'var(--pinkHi)',

        // Complete 48-Key Legacy Semantic Aliases (Theme-Scoped Contrast Tokens)
        'surface-container': 'var(--surface)',
        'on-tertiary-fixed-variant': 'var(--violet)',
        'surface-tint': 'var(--pink)',
        'tertiary-container': 'var(--surface2)',
        'surface-container-lowest': 'var(--bg)',
        'on-primary-fixed': '#000000',
        'error-container': 'var(--critBg)',
        background: 'var(--bg)',
        'surface-dim': 'var(--bg)',
        'on-surface-variant': 'var(--fg2)',
        'on-error-container': 'var(--onError)',
        'primary-fixed-dim': 'var(--pinkHi)',
        primary: 'var(--pink)',
        'surface-container-high': 'var(--surface2)',
        'on-tertiary-container': 'var(--fg2)',
        secondary: 'var(--violet)',
        'primary-fixed': 'var(--pink)',
        'on-surface': 'var(--fg)',
        'inverse-on-surface': 'var(--fg3)',
        'tertiary-fixed': 'var(--violet)',
        'inverse-surface': 'var(--surface3)',
        outline: 'var(--line2)',
        error: 'var(--crit)',
        success: 'var(--ok)',
        warning: 'var(--warn)',
        'on-primary-container': 'var(--onPrimary)',
        'on-primary-fixed-variant': 'var(--fg2)',
        'surface-bright': 'var(--surface2)',
        'surface-container-low': 'var(--bg)',
        'on-secondary-fixed': 'var(--onSecondary)',
        'inverse-primary': 'var(--pink)',
        'on-secondary': 'var(--onSecondary)',
        'on-background': 'var(--fg)',
        'surface-container-highest': 'var(--surface3)',
        'surface-variant': 'var(--surface2)',
        'secondary-fixed-dim': 'var(--violet)',
        tertiary: 'var(--violet)',
        'on-tertiary-fixed': 'var(--onTertiary)',
        'secondary-fixed': 'var(--violet)',
        'tertiary-fixed-dim': 'var(--violet)',
        'secondary-container': 'var(--surface2)',
        'on-error': 'var(--onError)',
        'on-secondary-container': 'var(--fg2)',
        'outline-variant': 'var(--line)',
        'on-secondary-fixed-variant': 'var(--fg2)',
        'on-primary': 'var(--onPrimary)',
        'primary-container': 'var(--pinkBg)',
        'on-tertiary': 'var(--onTertiary)',

        // Chain Colors (Synced to Nocturne)
        'chain-base': '#0052FF',
        'chain-arbitrum': 'var(--violet)',
        'chain-mainnet': 'var(--pink)',
        'chain-sonic': '#00e5ff',
        'chain-hyperliquid': 'var(--info)',
      },
      fontFamily: {
        headline: ['Inter', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        label: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      animation: {
        'fade-in': 'fadeIn 0.2s ease-out',
        'slide-in': 'slideIn 0.2s ease-out',
      },
      backgroundImage: {
        'brand-gradient': 'var(--grad)',
      },
      boxShadow: {
        neon: '0 0 15px rgba(255, 73, 164, 0.3), 0 0 30px rgba(184, 132, 255, 0.2)',
        'neon-strong': '0 0 20px rgba(255, 73, 164, 0.5), 0 0 40px rgba(184, 132, 255, 0.3)',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideIn: {
          '0%': { opacity: '0', transform: 'translateY(-20px) scale(0.95)' },
          '100%': { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
      },
    },
  },
  plugins: [
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    require('@tailwindcss/typography'),
  ],
}
