/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/config/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface-container": "#141c2e",
        "on-tertiary-fixed-variant": "#4d2a73",
        "surface-tint": "#7dd3fc",
        "tertiary-container": "#3d2060",
        "surface-container-lowest": "#0a0e1a",
        "on-primary-fixed": "#001f2e",
        "error-container": "#3d1414",
        "background": "#0a0e1a",
        "surface-dim": "#0f1524",
        "on-surface-variant": "#a0b4c4",
        "on-error-container": "#ffb3b3",
        "primary-fixed-dim": "#7dd3fc",
        "primary": "#7dd3fc",
        "surface-container-high": "#1a2438",
        "on-tertiary-container": "#e8d0ff",
        "secondary": "#88b4cc",
        "primary-fixed": "#c8eaff",
        "on-surface": "#e0e8f0",
        "inverse-on-surface": "#0a0e1a",
        "tertiary-fixed": "#e8d0ff",
        "inverse-surface": "#e0e8f0",
        "outline": "#4a6070",
        "error": "#ff6b6b",
        "on-primary-container": "#c8eaff",
        "on-primary-fixed-variant": "#004d73",
        "surface-bright": "#1a2438",
        "surface-container-low": "#111828",
        "on-secondary-fixed": "#0d1f2b",
        "inverse-primary": "#0a4c6e",
        "on-secondary": "#001f2e",
        "on-background": "#e0e8f0",
        "surface-container-highest": "#202c42",
        "surface-variant": "#1a2438",
        "secondary-fixed-dim": "#88b4cc",
        "tertiary": "#c8a0f0",
        "on-tertiary-fixed": "#1a002e",
        "secondary-fixed": "#c0d8e8",
        "tertiary-fixed-dim": "#c8a0f0",
        "secondary-container": "#1a3a4e",
        "on-error": "#1a0000",
        "on-secondary-container": "#c0d8e8",
        "outline-variant": "#2a3a48",
        "surface": "#0f1524",
        "on-secondary-fixed-variant": "#2a4a5e",
        "on-primary": "#001f2e",
        "primary-container": "#0e4d6e",
        "on-tertiary": "#1a002e",
        // Chain Colors
        "chain-base": "#0052FF",
        "chain-arbitrum": "#28a0f0",
        "chain-mainnet": "#94a3b8",
        "chain-sonic": "#00e5ff",
        "chain-hyperliquid": "#00ffa3",
      },
      fontFamily: {
        'headline': ['Inter', 'system-ui', 'sans-serif'],
        'body': ['Inter', 'system-ui', 'sans-serif'],
        'label': ['Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        'DEFAULT': '0.5rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px',
      },
      animation: {
        'fade-in': 'fadeIn 0.2s ease-out',
        'slide-in': 'slideIn 0.2s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideIn: {
          '0%': { opacity: '0', transform: 'translateY(-20px) scale(0.95)' },
          '100%': { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
      },
    },
  },
  plugins: [
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    require('@tailwindcss/typography'),
  ],
}
