module.exports = {
  darkMode: 'class',
  content: [
    './src/**/*.{js,ts,jsx,tsx}',
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#89acff',
        'primary-dim': '#5a90ff',
        'primary-container': '#739eff',
        secondary: '#68fadd',
        'secondary-dim': '#56ebcf',
        tertiary: '#e0f4ff',
        'tertiary-dim': '#bfd8e5',
        error: '#ff716c',
        success: '#86e6b4',
        warning: '#ffcf87',
        info: '#9ad8ff',
        surface: '#0d0e10',
        'surface-dim': '#0d0e10',
        'surface-bright': '#2b2c2f',
        'surface-container-lowest': '#000000',
        'surface-container-low': '#121316',
        'surface-container': '#181a1c',
        'surface-container-high': '#1e2022',
        'surface-container-highest': '#242629',
        background: '#0d0e10',
        'on-surface': '#fdfbfe',
        'on-surface-variant': '#ababad',
        'on-primary': '#002b6a',
        'on-secondary': '#005d4f',
        outline: '#757578',
        'outline-variant': '#47484a',
        // Legacy keys re-pointed to the semantic palette during the design-pass
        // migration; deleted once the class sweep shows zero remaining uses.
        'background-light': '#fdfbfe',
        'background-dark': '#0d0e10',
        charcoal: { 700: '#1e2022', 800: '#181a1c', 900: '#0d0e10' },
        magenta: { 500: '#89acff', 600: '#739eff', 700: '#5a90ff' },
        violet: { 400: '#a7c1ff', 500: '#89acff' },
      },
      boxShadow: {
        // token-derived from `primary` #89acff — keep in sync if primary changes
        glow: '0 0 0 2px rgba(137, 172, 255, 0.35)',
        card: '0 0 0 1px rgba(255, 255, 255, 0.06)',
        'neon-glow': '0 0 15px rgba(137, 172, 255, 0.25)',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '1rem',
        xl: '1rem',
        '2xl': '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['var(--font-manrope)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        display: ['var(--font-inter)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        sans: ['var(--font-inter)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      zIndex: {
        dropdown: '30',
        header: '40',
        modal: '50',
        toast: '60',
      },
    },
  },
  plugins: [],
}
