[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
evm_version = "cancun"
cbor_metadata = true
viaIR = true
fs_permissions = [
    { access = "read", path = "./scripts/config.json"},
    { access = "read", path = "./scripts/fleets/usdc-fleet-def-1.json"}
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
base = "${BASE_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

[etherscan]
sepolia = { key = "7KB7N6WAQJFFC2F5UP98RBTESZ11EK8X8W}" }
base = { key = "8M4JVVERCDQURGWJ6UIVQU23YNAQU9Y5PK"  }
#                   Paste TENDERLY_ACCESS_TOKEN            Chain ID         Verifier URL: RPC_URL/verify/etherscan
unknown_chain = { key = "${TENDERLY_ACCESS_KEY}", chain = 84537357, url = "${TENDERLY_VIRTUAL_TESTNET_RPC_URL}/verify/etherscan" }

[fmt]
sort_imports=true
contract_new_lines=true
numer_underscoer='thousands'
wrap_comments=true

