packages:
  - 'packages/**'
  - '!**/test/**'
  - '!packages/core-contracts/lib/**'
  - '!packages/gov-contracts/lib/**'
  - '!packages/dutch-auction/lib/**'
  - '!packages/voting-decay/lib/**'
  - '!packages/external-dependencies/lib/**'
