// GENERATED — do not edit by hand.
// Source: config/{network}.json proxy addresses (`*-feed-proxy`); the matching
// impl addresses are resolved at prepare-time by `scripts/prepare.mjs` via
// `cast call <proxy> 'aggregator()(address)' --block $FEED_START_BLOCK`.
// Regenerated by `pnpm run prepare:{network}`.
import { Address } from '@graphprotocol/graph-ts'

const USDC_IMPL: string = '{{usdc-feed-aggregator}}'
const USDC_PROXY: string = '{{usdc-feed-proxy}}'
const ETH_IMPL: string = '{{eth-feed-aggregator}}'
const ETH_PROXY: string = '{{eth-feed-proxy}}'

// Resolve a bootstrap impl address (from `dataSource.address()`) back to
// the proxy address the FE indexes against. Single linear `if` chain —
// AssemblyScript renders this fine; the array-of-struct shape we tried
// earlier crashed the AS compiler.
export function proxyForBootstrapImpl(impl: Address): Address {
  const implHex = impl.toHexString().toLowerCase()
  if (implHex == USDC_IMPL.toLowerCase()) {
    return Address.fromString(USDC_PROXY)
  }
  if (implHex == ETH_IMPL.toLowerCase()) {
    return Address.fromString(ETH_PROXY)
  }
  return Address.zero()
}
