sources:
  - name: Base
    handler:
      graphql:
        endpoint: https://subgraph.staging.oasisapp.dev/summer-protocol-base
  - name: Sonic
    handler:
      graphql:
        endpoint: https://subgraph.staging.oasisapp.dev/summer-protocol-sonic
  - name: Arbitrum
    handler:
      graphql:
        endpoint: https://subgraph.staging.oasisapp.dev/summer-protocol-arbitrum
  - name: Mainnet
    handler:
      graphql:
        endpoint: https://subgraph.staging.oasisapp.dev/summer-protocol

serve:
  port: 4000
  playground: true 