[profile.default]
src = "src"
out = "out"
libs = [
  'node_modules', 
  'lib'
]
test = 'test'
cache_path  = 'cache_forge'
solc = "0.8.28"
viaIR = true
optimizer = false
evm_version = "cancun"
cbor_metadata = true

[profile.test]
src = "src"
out = "out"
libs = [
  'node_modules', 
  'lib'
]
test = 'test'
cache_path  = 'cache_forge'
solc = "0.8.28"
evm_version = "cancun"
cbor_metadata = true
viaIR = true
optimizer = false
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "remove"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true
  sort_imports = true
  contract_new_lines = true

[rpc_endpoints]
# Testnets
sepolia = "${SEPOLIA_RPC_URL}"

# Mainnets
base = "${BASE_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

[etherscan]
sepolia = { key = "7KB7N6WAQJFFC2F5UP98RBTESZ11EK8X8W}" }
base = { key = "8M4JVVERCDQURGWJ6UIVQU23YNAQU9Y5PK"  }
#                   Paste TENDERLY_ACCESS_TOKEN            Chain ID         Verifier URL: RPC_URL/verify/etherscan
unknown_chain = { key = "${TENDERLY_ACCESS_KEY}", chain = 84537357, url = "${TENDERLY_VIRTUAL_TESTNET_RPC_URL}/verify/etherscan" }