import fs from 'node:fs'
import path from 'node:path'

import hre from 'hardhat'
import kleur from 'kleur'
import prompts from 'prompts'
import { Address, encodeFunctionData, getAddress, Hex } from 'viem'

import { HUB_CHAIN_ID, HUB_CHAIN_NAME } from '../../common/constants'
import { ChainName, getChainConfigByChainName } from '../../helpers/chain-configs'
import { ChainSetup } from '../../helpers/chain-prompt'
import { buildCrossChainProposalAction } from '../../helpers/cross-chain-proposal'
import { getChainId } from '../../helpers/get-chainid'
import { promptForConfigType } from '../../helpers/prompt-helpers'
import { createGovernanceProposal } from '../../helpers/proposal-helpers'
import {
  BatchAction,
  buildTx,
  SafeAbiFunctionFragment,
  writeSafeBatch,
} from '../../helpers/safe-tx-builder'
import {
  arkAbi,
  arkWithdrawalViewAbi,
  CleanupArkEntry,
  cleanupConfigDir,
  CURATOR_ROLE_ENUM,
  erc20Abi,
  fleetAbi,
  FleetCleanupConfig,
  formatAssets,
  isCleanupAction,
  KEEPER_ROLE_ENUM,
  pamViewAbi,
  parseDetailsJson,
  proposalsDir,
  raftViewAbi,
  sanitizeFleetName,
  WITHDRAWAL_REQUEST_MAX,
  writeAbis,
} from './common'

/**
 * Reads the edited fleet-cleanup configs (config/fleet-cleanup/<network>/*.json, generated by
 * `gov:cleanup-fleets:init`) and emits ONE output per fleet with any non-`leave` ark action.
 *
 * Two output modes (MODE env, default `proposal`):
 *  - `proposal` — an on-chain SummerGovernor proposal (JSON compatible with `gov:submit-proposal`
 *    / `gov:execute-proposal`), created on the BASE hub. For a satellite fleet (e.g. mainnet) the
 *    fleet actions are wrapped in `sendProposalToTargetChain` → LayerZero → the fleet-chain
 *    timelock, which is the executor. For a hub (Base) fleet the actions are inlined.
 *  - `safe` — a Safe Transaction Builder batch executed by a governor Safe (the prior behavior).
 *
 * The per-fleet ordered action list (executed by the timelock in proposal mode, or the Safe in
 * safe mode — referred to below as the "executor"):
 *   1. PAM.grantKeeperRole(ark, executor)     — per requestWithdrawal ark, ark-scoped, if missing
 *   2. FleetCommander.unpause()               — only if paused AND there is a whenNotPaused action
 *   3. PAM.grantCuratorRole(fleet, executor)  — if a sweep needs whitelisting or a cap must be zeroed
 *   4. per sweep ark: setSweepableToken(true) → setNonSweepableToken(false) →
 *      Raft.socializeLosses(ark, [pool], receiver) → flags restored
 *   5. per removal ark: setArkDepositCap(ark, 0) (if cap > 0) then removeArk(ark)
 *   6. Ark.requestWithdrawal(max)             — per requestWithdrawal ark (async; ark stays)
 *   7. PAM.revokeCuratorRole / revokeKeeperRole — revoke the transient roles granted in 1 & 3
 *      (the follow-up settlement proposal re-grants keeper)
 *   8. FleetCommander.pause()                 — if repauseAfter AND the fleet ends unpaused
 *
 * Every action is re-validated against LIVE chain state — the config's numbers are the operator's
 * worksheet, not the source of truth.
 *
 * Non-interactive usage (all optional, prompts otherwise):
 *   MODE=proposal|safe BUMMER=true|false SAFE_ADDRESS=0x.. RECEIVER=0x.. FLEETS=0x..,0x.. \
 *     LZ_GAS_LIMIT=350000 YES=1 NETWORK=mainnet pnpm gov:cleanup-fleets
 */

type Mode = 'proposal' | 'safe'

interface ArkWorkItem {
  entry: CleanupArkEntry
  liveTotalAssets: bigint
  liveDepositCap: bigint
  pool?: Address
  poolSymbol?: string
  poolBalance?: bigint
  isSweepable?: boolean
  isNonSweepable?: boolean
  executorHasKeeper?: boolean
  pendingRequestId?: bigint
}

interface FleetWorkPlan {
  config: FleetCleanupConfig
  file: string
  livePaused: boolean
  unpauseNotBefore?: Date
  executorHasCurator: boolean
  sweeps: ArkWorkItem[]
  removals: ArkWorkItem[]
  withdrawals: ArkWorkItem[]
}

interface PlannedAction {
  target: Address
  fragment: SafeAbiFunctionFragment
  args: readonly unknown[]
  summary: string
}

function fail(message: string): never {
  console.log(kleur.red(`❌ ${message}`))
  process.exit(1)
}

async function promptForAddressWithDefault(message: string, initial: Address): Promise<Address> {
  const { value } = await prompts({
    type: 'text',
    name: 'value',
    message,
    initial,
    validate: (val: string) => (/^0x[a-fA-F0-9]{40}$/.test(val.trim()) ? true : 'Invalid address'),
  })
  if (!value) {
    throw new Error('Address input is required')
  }
  return getAddress(value.trim())
}

async function resolveMode(): Promise<Mode> {
  if (process.env.MODE === 'proposal' || process.env.MODE === 'safe') return process.env.MODE
  if (process.env.MODE !== undefined) {
    fail(`Invalid MODE "${process.env.MODE}" — expected "proposal" or "safe".`)
  }
  if (process.env.YES === '1') return 'proposal' // non-interactive default
  const { mode } = await prompts({
    type: 'select',
    name: 'mode',
    message: 'Output mode:',
    choices: [
      { title: 'Governance proposal (default)', value: 'proposal' },
      { title: 'Safe transaction batch', value: 'safe' },
    ],
    initial: 0,
  })
  return (mode as Mode) ?? 'proposal'
}

/**
 * Builds the ordered, chain-agnostic action list for one fleet. Targets are real contract
 * addresses; role grants target `executor` (the Safe in safe mode, or the timelock in proposal
 * mode). Both emitters consume this identical list.
 */
function buildFleetActions(
  plan: FleetWorkPlan,
  ctx: {
    executor: Address
    fleet: Address
    pamAddress: Address
    raftAddress: Address
    receiver: Address
  },
): { actions: PlannedAction[]; willUnpause: boolean; willRepause: boolean } {
  const { config: fc } = plan
  const { executor, fleet, pamAddress, raftAddress, receiver } = ctx
  const actions: PlannedAction[] = []

  const capRemovals = plan.removals.filter((r) => r.liveDepositCap > 0n)
  const hasWhenNotPausedAction = plan.removals.length > 0 || capRemovals.length > 0
  const willUnpause = plan.livePaused && hasWhenNotPausedAction
  const fleetUnpausedAtEnd = willUnpause || !plan.livePaused
  const willRepause = fc.repauseAfter && fleetUnpausedAtEnd

  // 1. Ark-scoped keeper grants for requestWithdrawal arks. Only granted where the executor
  //    doesn't already hold it; revoked again at the end (step 8) — the follow-up settlement
  //    proposal re-grants it.
  const keeperGrantArks = plan.withdrawals.filter((w) => !w.executorHasKeeper)
  for (const w of keeperGrantArks) {
    actions.push({
      target: pamAddress,
      fragment: writeAbis.grantKeeperRole,
      args: [w.entry.address, executor],
      summary: `PAM.grantKeeperRole(${w.entry.name} ark, executor) — ark-scoped, for requestWithdrawal`,
    })
  }

  // 2. unpause (only needed for whenNotPaused actions: removeArk / setArkDepositCap)
  if (willUnpause) {
    actions.push({
      target: fleet,
      fragment: writeAbis.unpause,
      args: [],
      summary: `FleetCommander(${fc.fleetName}).unpause() — not before ${plan.unpauseNotBefore?.toISOString()}`,
    })
  }

  // 3. curator grant (transient) if a sweep needs whitelisting or a cap must be zeroed
  const needsCurator = plan.sweeps.some((s) => !s.isSweepable) || capRemovals.length > 0
  const grantCurator = needsCurator && !plan.executorHasCurator
  if (grantCurator) {
    actions.push({
      target: pamAddress,
      fragment: writeAbis.grantCuratorRole,
      args: [fleet, executor],
      summary: `PAM.grantCuratorRole(${fc.fleetName}, executor) — temporary, for setSweepableToken/setArkDepositCap`,
    })
  }

  // 4. sweep round-trips
  for (const s of plan.sweeps) {
    if (!s.isSweepable) {
      actions.push({
        target: raftAddress,
        fragment: writeAbis.setSweepableToken,
        args: [s.entry.address, s.pool!, true],
        summary: `Raft.setSweepableToken(${s.entry.name}, ${s.poolSymbol}, true)`,
      })
    }
    if (s.isNonSweepable) {
      actions.push({
        target: raftAddress,
        fragment: writeAbis.setNonSweepableToken,
        args: [s.entry.address, s.pool!, false],
        summary: `Raft.setNonSweepableToken(${s.entry.name}, ${s.poolSymbol}, false) — lift blacklist`,
      })
    }
    actions.push({
      target: raftAddress,
      fragment: writeAbis.socializeLosses,
      args: [s.entry.address, [s.pool!], receiver],
      summary: `Raft.socializeLosses(${s.entry.name}, [${s.poolSymbol}], ${receiver}) — sweeps ${s.poolBalance} shares`,
    })
    if (s.isNonSweepable) {
      actions.push({
        target: raftAddress,
        fragment: writeAbis.setNonSweepableToken,
        args: [s.entry.address, s.pool!, true],
        summary: `Raft.setNonSweepableToken(${s.entry.name}, ${s.poolSymbol}, true) — restore blacklist`,
      })
    }
    if (!s.isSweepable) {
      actions.push({
        target: raftAddress,
        fragment: writeAbis.setSweepableToken,
        args: [s.entry.address, s.pool!, false],
        summary: `Raft.setSweepableToken(${s.entry.name}, ${s.poolSymbol}, false) — restore whitelist`,
      })
    }
  }

  // 5. removals: zero cap (if needed) then removeArk
  for (const r of capRemovals) {
    actions.push({
      target: fleet,
      fragment: writeAbis.setArkDepositCap,
      args: [r.entry.address, 0n],
      summary: `FleetCommander.setArkDepositCap(${r.entry.name}, 0)`,
    })
  }
  for (const r of plan.removals) {
    actions.push({
      target: fleet,
      fragment: writeAbis.removeArk,
      args: [r.entry.address],
      summary: `FleetCommander(${fc.fleetName}).removeArk(${r.entry.name})`,
    })
  }

  // 6. requestWithdrawal (async — ark stays in the fleet)
  for (const w of plan.withdrawals) {
    actions.push({
      target: w.entry.address,
      fragment: writeAbis.requestWithdrawal,
      args: [WITHDRAWAL_REQUEST_MAX],
      summary: `${w.entry.name}.requestWithdrawal(max) — async redemption of the full position`,
    })
  }

  // 7. revoke the transient roles we granted (both curator and the ark-scoped keeper). The
  //    follow-up settlement proposal (claimWithdrawal/sweep/removeArk) re-grants keeper.
  if (grantCurator) {
    actions.push({
      target: pamAddress,
      fragment: writeAbis.revokeCuratorRole,
      args: [fleet, executor],
      summary: `PAM.revokeCuratorRole(${fc.fleetName}, executor) — cleanup`,
    })
  }
  for (const w of keeperGrantArks) {
    actions.push({
      target: pamAddress,
      fragment: writeAbis.revokeKeeperRole,
      args: [w.entry.address, executor],
      summary: `PAM.revokeKeeperRole(${w.entry.name} ark, executor) — cleanup (re-granted in the follow-up)`,
    })
  }

  // 8. re-pause
  if (willRepause) {
    actions.push({
      target: fleet,
      fragment: writeAbis.pause,
      args: [],
      summary: `FleetCommander(${fc.fleetName}).pause() — restore paused state (restarts the minimum pause window)`,
    })
  }

  return { actions, willUnpause, willRepause }
}

function encodePlanned(a: PlannedAction): { target: Address; value: bigint; calldata: Hex } {
  return {
    target: a.target,
    value: 0n,
    calldata: encodeFunctionData({
      abi: [a.fragment],
      functionName: a.fragment.name,
      args: a.args as never,
    }) as Hex,
  }
}

async function main() {
  const network = hre.network.name
  const chainId = getChainId()
  console.log(kleur.blue('Network:'), kleur.cyan(`${network} (chainId ${chainId})`))

  const mode = await resolveMode()
  console.log(kleur.blue('Mode:'), kleur.cyan(mode))

  const useBummerConfig =
    process.env.BUMMER !== undefined ? process.env.BUMMER === 'true' : await promptForConfigType()

  // Source every address from the fleet-chain config (getChainConfigByChainName reads the real
  // per-chain block from index.json — avoids the MAINNET→base alias bug in config/index.ts).
  const fleetChainSetup: ChainSetup = {
    name: network as ChainName,
    ...getChainConfigByChainName(network as ChainName, useBummerConfig),
  }
  const dc = fleetChainSetup.config.deployedContracts
  const raftAddress = getAddress(dc.core.raft.address)
  const pamAddress = getAddress(dc.gov.protocolAccessManager.address)
  const foundationAddress = getAddress(fleetChainSetup.config.common.foundation)
  const fleetChainTimelock = getAddress(dc.govV2.timelock.address)

  const hubSetup = getChainConfigByChainName(HUB_CHAIN_NAME as ChainName, useBummerConfig)
  const hubGovernor = getAddress(hubSetup.config.deployedContracts.govV2.summerGovernor.address)
  const fleetIsHub = network === HUB_CHAIN_NAME
  const lzGasLimit = process.env.LZ_GAS_LIMIT ? BigInt(process.env.LZ_GAS_LIMIT) : 350000n

  const publicClient = await hre.viem.getPublicClient()

  // Executor: the account that runs the actions and receives the transient roles.
  let executor: Address
  let safeAddress: Address | undefined
  if (mode === 'safe') {
    safeAddress = process.env.SAFE_ADDRESS
      ? getAddress(process.env.SAFE_ADDRESS)
      : await promptForAddressWithDefault(
          'Governor Safe address (executes the batches):',
          foundationAddress,
        )
    executor = safeAddress
  } else {
    executor = fleetChainTimelock
    console.log(
      kleur.blue('Executor (satellite/hub timelock):'),
      kleur.cyan(executor),
      fleetIsHub
        ? kleur.gray('(hub)')
        : kleur.gray(`(satellite → created on ${HUB_CHAIN_NAME} hub)`),
    )
  }
  const receiverAddress = process.env.RECEIVER
    ? getAddress(process.env.RECEIVER)
    : mode === 'safe'
      ? await promptForAddressWithDefault('Receiver of the swept tokens:', executor)
      : foundationAddress

  // ---- Load fleet configs ----
  const dir = cleanupConfigDir(network)
  if (!fs.existsSync(dir)) {
    fail(`No fleet-cleanup configs at ${dir} — run gov:cleanup-fleets:init first.`)
  }
  const fleetFilter = process.env.FLEETS
    ? new Set(process.env.FLEETS.split(',').map((a) => getAddress(a.trim())))
    : null

  const files = fs
    .readdirSync(dir)
    .filter((f) => f.endsWith('.json'))
    .map((f) => path.join(dir, f))

  const expectedConfigType = useBummerConfig ? 'test' : 'prod'
  const candidates: { file: string; config: FleetCleanupConfig }[] = []
  for (const file of files) {
    const parsed = JSON.parse(fs.readFileSync(file, 'utf8')) as FleetCleanupConfig
    if (fleetFilter && !fleetFilter.has(getAddress(parsed.fleetAddress))) continue
    if (parsed.chainId !== chainId) {
      fail(
        `${path.basename(file)} was generated for chainId ${parsed.chainId}, current is ${chainId}.`,
      )
    }
    if (parsed.configType !== expectedConfigType) {
      fail(
        `${path.basename(file)} was generated for configType "${parsed.configType}" but you selected "${expectedConfigType}" (BUMMER mismatch).`,
      )
    }
    for (const ark of parsed.arks) {
      if (!isCleanupAction(ark.action)) {
        fail(`${path.basename(file)}: ark ${ark.address} has invalid action "${ark.action}".`)
      }
      if (ark.isBufferArk && ark.action !== 'leave') {
        fail(`${path.basename(file)}: buffer ark ${ark.address} must have action "leave".`)
      }
    }
    if (parsed.arks.some((a) => a.action !== 'leave')) {
      candidates.push({ file, config: parsed })
    }
  }
  if (candidates.length === 0) {
    console.log(kleur.yellow('No fleet config has a non-"leave" action — nothing to do.'))
    return
  }

  // Executor must hold GOVERNOR_ROLE (checked on the fleet chain, where actions execute).
  const governorRole = await publicClient.readContract({
    address: pamAddress,
    abi: pamViewAbi,
    functionName: 'GOVERNOR_ROLE',
  })
  const executorIsGovernor = await publicClient.readContract({
    address: pamAddress,
    abi: pamViewAbi,
    functionName: 'hasRole',
    args: [governorRole, executor],
  })
  if (!executorIsGovernor) {
    fail(`Executor ${executor} does not hold GOVERNOR_ROLE on ProtocolAccessManager ${pamAddress}.`)
  }
  console.log(kleur.green(`✓ executor ${executor} holds GOVERNOR_ROLE`))

  // ---- Re-validate each fleet's plan against live chain state ----
  const plans: FleetWorkPlan[] = []
  for (const { file, config: fleetConfig } of candidates) {
    const fleetAddress = getAddress(fleetConfig.fleetAddress)
    console.log(kleur.blue(`\nValidating ${fleetConfig.fleetName} (${fleetAddress})…`))

    const [livePaused, pauseStartTime, minimumPauseTime, liveActiveArks, liveBufferArk] =
      await Promise.all([
        publicClient.readContract({ address: fleetAddress, abi: fleetAbi, functionName: 'paused' }),
        publicClient.readContract({
          address: fleetAddress,
          abi: fleetAbi,
          functionName: 'pauseStartTime',
        }),
        publicClient.readContract({
          address: fleetAddress,
          abi: fleetAbi,
          functionName: 'minimumPauseTime',
        }),
        publicClient.readContract({
          address: fleetAddress,
          abi: fleetAbi,
          functionName: 'getActiveArks',
        }),
        publicClient.readContract({
          address: fleetAddress,
          abi: fleetAbi,
          functionName: 'bufferArk',
        }),
      ])
    const activeArkSet = new Set(liveActiveArks.map((a) => getAddress(a)))

    const curatorRole = await publicClient.readContract({
      address: pamAddress,
      abi: pamViewAbi,
      functionName: 'generateRole',
      args: [CURATOR_ROLE_ENUM, fleetAddress],
    })
    const executorHasCurator = await publicClient.readContract({
      address: pamAddress,
      abi: pamViewAbi,
      functionName: 'hasRole',
      args: [curatorRole, executor],
    })

    const plan: FleetWorkPlan = {
      config: fleetConfig,
      file,
      livePaused,
      unpauseNotBefore: livePaused
        ? new Date(Number(pauseStartTime + minimumPauseTime) * 1000)
        : undefined,
      executorHasCurator,
      sweeps: [],
      removals: [],
      withdrawals: [],
    }

    for (const entry of fleetConfig.arks.filter((a) => a.action !== 'leave')) {
      const arkAddress = getAddress(entry.address)
      if (arkAddress === getAddress(liveBufferArk)) {
        fail(`${entry.name} (${arkAddress}) is the live buffer ark of ${fleetAddress}.`)
      }
      if (!activeArkSet.has(arkAddress)) {
        fail(
          `${entry.name} (${arkAddress}) is not an active ark of fleet ${fleetAddress} (already removed?).`,
        )
      }

      const [liveTotalAssets, liveDepositCap, liveDetailsJson] = await Promise.all([
        publicClient.readContract({
          address: arkAddress,
          abi: arkAbi,
          functionName: 'totalAssets',
        }),
        publicClient.readContract({ address: arkAddress, abi: arkAbi, functionName: 'depositCap' }),
        publicClient.readContract({ address: arkAddress, abi: arkAbi, functionName: 'details' }),
      ])
      const item: ArkWorkItem = { entry, liveTotalAssets, liveDepositCap }

      // requestWithdrawal: async redemption — ark stays, not swept, not removed here.
      if (entry.action === 'requestWithdrawal') {
        try {
          await publicClient.readContract({
            address: arkAddress,
            abi: arkWithdrawalViewAbi,
            functionName: 'isWithdrawalClaimRequired',
          })
        } catch {
          fail(
            `${entry.name} (${arkAddress}) does not implement IArkWithWithdrawalRequest — ` +
              `"requestWithdrawal" is only valid for async-withdrawal arks (Origin/Syrup/…).`,
          )
        }
        let pendingRequestId = 0n
        try {
          pendingRequestId = await publicClient.readContract({
            address: arkAddress,
            abi: arkWithdrawalViewAbi,
            functionName: 'withdrawalRequestId',
          })
        } catch {
          // some arks expose it as public state only via a different selector — non-fatal
        }
        if (pendingRequestId > 0n) {
          console.log(
            kleur.yellow(
              `  ⚠ ${entry.name} already has a pending withdrawal request (id ${pendingRequestId}). ` +
                `Origin/SyrupV2 would revert WithdrawalAlreadyRequested; SyrupV1 would double-request.`,
            ),
          )
        }
        item.pendingRequestId = pendingRequestId
        const keeperRole = await publicClient.readContract({
          address: pamAddress,
          abi: pamViewAbi,
          functionName: 'generateRole',
          args: [KEEPER_ROLE_ENUM, arkAddress],
        })
        item.executorHasKeeper = await publicClient.readContract({
          address: pamAddress,
          abi: pamViewAbi,
          functionName: 'hasRole',
          args: [keeperRole, executor],
        })
        plan.withdrawals.push(item)
        continue
      }

      const wantsSweep =
        entry.action === 'socializeLosses' || entry.action === 'socializeLossesAndRemove'
      const wantsRemoval =
        entry.action === 'socializeLossesAndRemove' || entry.action === 'removeArk'

      if (wantsSweep) {
        if (liveTotalAssets === 0n) {
          fail(
            `${entry.name} (${arkAddress}) has live totalAssets == 0 — nothing to socialize. ` +
              `Config is stale; use action "removeArk" instead if removal is intended.`,
          )
        }
        const { pool } = parseDetailsJson(liveDetailsJson)
        if (!pool) {
          fail(
            `${entry.name} (${arkAddress}) has assets but details() has no usable "pool" address ` +
              `(${liveDetailsJson}) — handle manually.`,
          )
        }
        const poolBalance = await publicClient.readContract({
          address: pool,
          abi: erc20Abi,
          functionName: 'balanceOf',
          args: [arkAddress],
        })
        if (poolBalance === 0n) {
          fail(
            `${entry.name} (${arkAddress}) reports totalAssets ${liveTotalAssets} but holds no balance ` +
              `of details().pool token ${pool}. Sweeping would not zero totalAssets — handle manually.`,
          )
        }
        let poolSymbol = '???'
        try {
          poolSymbol = await publicClient.readContract({
            address: pool,
            abi: erc20Abi,
            functionName: 'symbol',
          })
        } catch {
          // non-standard token symbol — cosmetic only
        }
        const [isSweepable, isNonSweepable] = await Promise.all([
          publicClient.readContract({
            address: raftAddress,
            abi: raftViewAbi,
            functionName: 'sweepableTokens',
            args: [arkAddress, pool],
          }),
          publicClient.readContract({
            address: raftAddress,
            abi: raftViewAbi,
            functionName: 'nonSweepableTokens',
            args: [arkAddress, pool],
          }),
        ])
        item.pool = pool
        item.poolSymbol = poolSymbol
        item.poolBalance = poolBalance
        item.isSweepable = isSweepable
        item.isNonSweepable = isNonSweepable
        plan.sweeps.push(item)
      }

      if (wantsRemoval) {
        if (entry.action === 'removeArk' && liveTotalAssets > 0n) {
          fail(
            `${entry.name} (${arkAddress}) has live totalAssets ${liveTotalAssets} — plain "removeArk" ` +
              `would revert (FleetCommanderArkAssetsNotZero). Use "socializeLossesAndRemove" or "requestWithdrawal".`,
          )
        }
        plan.removals.push(item)
      }
    }

    plans.push(plan)
  }

  // ---- Summary — these outputs move user-fund backing / wind fleets down, make it loud ----
  console.log(kleur.cyan().bold('\n================ Cleanup plan ================'))
  for (const plan of plans) {
    const { config: fc } = plan
    console.log(kleur.yellow(`\nFleet ${fc.fleetName} (${fc.fleetAddress})`))
    console.log(
      `  paused         : ${plan.livePaused}${plan.unpauseNotBefore ? ` (unpause executable after ${plan.unpauseNotBefore.toISOString()})` : ''}`,
    )
    console.log(`  repause after  : ${fc.repauseAfter}`)
    for (const s of plan.sweeps) {
      console.log(
        kleur.red(
          `  sweep          : ${s.entry.name} — ${formatAssets(s.liveTotalAssets, fc.assetDecimals, fc.assetSymbol)} ` +
            `backed by ${s.poolBalance} ${s.poolSymbol} (${s.pool}) → ${receiverAddress}`,
        ),
      )
    }
    for (const w of plan.withdrawals) {
      console.log(
        kleur.magenta(
          `  requestWithdraw: ${w.entry.name} (${w.entry.address}) — ${formatAssets(w.liveTotalAssets, fc.assetDecimals, fc.assetSymbol)} async (ark stays)`,
        ),
      )
    }
    for (const r of plan.removals) {
      console.log(
        kleur.yellow(
          `  removeArk      : ${r.entry.name} (${r.entry.address}) — live cap ${r.liveDepositCap}, live assets ${r.liveTotalAssets}`,
        ),
      )
    }
  }
  const sweepCount = plans.reduce((n, p) => n + p.sweeps.length, 0)
  if (sweepCount > 0) {
    console.log(
      kleur
        .red()
        .bold(
          `\n⚠️  Sweeping removes the assets backing ${sweepCount} ark(s) from fleet accounting` +
            ` (fleet share price will drop accordingly — this socializes the losses).`,
        ),
    )
  }

  if (process.env.YES !== '1') {
    const { confirmed } = await prompts({
      type: 'confirm',
      name: 'confirmed',
      message: `Build ${plans.length} ${mode === 'proposal' ? 'governance proposal(s)' : 'Safe batch(es)'} for this plan?`,
      initial: false,
    })
    if (!confirmed) {
      console.log(kleur.red('Operation cancelled by user.'))
      return
    }
  }

  // ---- Emit one output per fleet ----
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-')
  const prefix = useBummerConfig ? 'test' : 'prod'
  const writtenFiles: string[] = []

  for (const plan of plans) {
    const { config: fc } = plan
    const fleetAddress = getAddress(fc.fleetAddress)
    const { actions } = buildFleetActions(plan, {
      executor,
      fleet: fleetAddress,
      pamAddress,
      raftAddress,
      receiver: receiverAddress,
    })

    if (actions.length === 0) {
      console.log(kleur.gray(`\n${fc.fleetName}: no actions after validation — skipped.`))
      continue
    }

    console.log(
      kleur.cyan().bold(`\n${mode === 'proposal' ? 'Proposal' : 'Batch'} — ${fc.fleetName}`),
    )
    actions.forEach((a, i) => console.log(kleur.yellow(`  ${i + 1}. ${a.summary}`)))

    const actionSummary = actions.map((a) => a.summary)
    const description = buildDescription(mode, fc, plan, actions, {
      executor,
      fleetIsHub,
      network,
    })

    if (mode === 'safe') {
      const batchActions: BatchAction[] = actions.map((a) => ({
        tx: buildTx(a.target, a.fragment, a.args),
        summary: a.summary,
      }))
      const outFile = path.join(
        proposalsDir(),
        `${prefix}_fleet_cleanup_${sanitizeFleetName(fc.fleetName)}_${network}_${timestamp}.json`,
      )
      writtenFiles.push(
        writeSafeBatch(
          batchActions,
          {
            name: `Fleet cleanup — ${fc.fleetName}`,
            description,
            safeAddress: safeAddress!,
            chainId,
          },
          outFile,
        ),
      )
    } else {
      const dstActions = actions.map(encodePlanned)
      let srcActions: { target: Address; value: bigint; calldata: Hex }[]
      let crossChainExecution:
        | { name: string; chainId: number; targets: string[]; values: string[]; datas: string[] }[]
        | undefined

      if (fleetIsHub) {
        srcActions = dstActions
        crossChainExecution = undefined
      } else {
        const hubAction = await buildCrossChainProposalAction({
          targetChain: fleetChainSetup,
          targets: dstActions.map((a) => a.target),
          values: dstActions.map((a) => a.value),
          calldatas: dstActions.map((a) => a.calldata),
          description,
          governorAddress: hubGovernor,
          gasLimit: lzGasLimit,
        })
        srcActions = [hubAction]
        crossChainExecution = [
          {
            name: fleetChainSetup.name,
            chainId,
            targets: dstActions.map((a) => a.target as string),
            values: dstActions.map((a) => a.value.toString()),
            datas: dstActions.map((a) => a.calldata as string),
          },
        ]
      }

      const savePath = path.join(
        proposalsDir(),
        `${prefix}_fleet_cleanup_proposal_${sanitizeFleetName(fc.fleetName)}_${network}_${timestamp}.json`,
      )
      await createGovernanceProposal(
        `Fleet cleanup — ${fc.fleetName} (${network})`,
        description,
        srcActions,
        hubGovernor,
        HUB_CHAIN_ID,
        '',
        actionSummary,
        savePath,
        crossChainExecution,
      )
      writtenFiles.push(savePath)
    }
  }

  console.log(kleur.green().bold(`\n✅ ${writtenFiles.length} ${mode} file(s) written:`))
  for (const f of writtenFiles) console.log(kleur.green(`   ${f}`))

  const futureUnpauses = plans.filter(
    (p) => p.livePaused && p.unpauseNotBefore && p.unpauseNotBefore.getTime() > Date.now(),
  )
  for (const p of futureUnpauses) {
    console.log(
      kleur
        .red()
        .bold(
          `⚠️  ${p.config.fleetName}: unpause reverts if executed before ${p.unpauseNotBefore!.toISOString()} (minimum pause time).`,
        ),
    )
  }

  if (mode === 'safe') {
    console.log(
      kleur.cyan(
        '\nImport each file in the Safe web UI: Apps → Transaction Builder → drag & drop the JSON, review the decoded actions, collect signatures.',
      ),
    )
  } else {
    console.log(
      kleur.cyan(
        `\nSubmit each proposal on the ${HUB_CHAIN_NAME} hub with: NETWORK=${HUB_CHAIN_NAME} pnpm gov:submit-proposal (point it at the JSON).`,
      ),
    )
    if (!fleetIsHub) {
      console.log(
        kleur.yellow(
          `⚠️  Cross-chain: the ${HUB_CHAIN_NAME} hub governor ${hubGovernor} must hold native gas to pay the LayerZero fee ` +
            `when sendProposalToTargetChain executes (see scripts/governance/sample/fund-governor.ts).`,
        ),
      )
    }
  }
  console.log(
    kleur.gray(
      '\nAfter execution, update the fleet deployment JSON (deployments/fleets/), curation arks.json, ' +
        'and regenerate the fleet-cleanup config (FORCE=1). requestWithdrawal arks need a follow-up ' +
        'proposal (claimWithdrawal on Origin, sweep both, then removeArk) once positions settle.',
    ),
  )
}

function buildDescription(
  mode: Mode,
  fc: FleetCleanupConfig,
  plan: FleetWorkPlan,
  actions: PlannedAction[],
  meta: { executor: Address; fleetIsHub: boolean; network: string },
): string {
  const lines = actions.map((a, i) => `${i + 1}. ${a.summary}`).join('\n')
  const routing =
    mode === 'proposal'
      ? meta.fleetIsHub
        ? `Executed on the ${HUB_CHAIN_NAME} hub by the timelock ${meta.executor}.`
        : `Created on the ${HUB_CHAIN_NAME} hub and relayed via LayerZero to the ${meta.network} timelock ${meta.executor} for execution.`
      : `Executed by the governor Safe ${meta.executor}.`
  const pauseNote =
    plan.livePaused && plan.unpauseNotBefore
      ? `\n\nThe fleet is currently paused; unpause is only executable after ${plan.unpauseNotBefore.toISOString()} (minimum pause time).`
      : ''
  return `# Fleet cleanup — ${fc.fleetName}\n\n` + `${routing}\n\n## Actions\n${lines}${pauseNote}`
}

main().catch((error) => {
  console.error(kleur.red().bold('An error occurred:'), error)
  process.exit(1)
})
