import fs from 'node:fs'
import path from 'node:path'

import hre from 'hardhat'
import kleur from 'kleur'
import prompts from 'prompts'
import { Address, getAddress } from 'viem'

import { BaseConfig } from '../../../types/config-types'
import { getConfigByNetwork } from '../../helpers/config-handler'
import { getChainId } from '../../helpers/get-chainid'
import { promptForConfigType } from '../../helpers/prompt-helpers'
import { BatchAction, buildTx, printActions, writeSafeBatch } from '../../helpers/safe-tx-builder'
import {
  arkAbi,
  CleanupArkEntry,
  cleanupConfigDir,
  CURATOR_ROLE_ENUM,
  erc20Abi,
  fleetAbi,
  FleetCleanupConfig,
  formatAssets,
  isCleanupAction,
  pamViewAbi,
  parseDetailsJson,
  proposalsDir,
  raftViewAbi,
  sanitizeFleetName,
  writeAbis,
} from './common'

/**
 * Reads the edited fleet-cleanup configs (config/fleet-cleanup/<network>/*.json, generated by
 * `gov:cleanup-fleets:init`) and emits ONE Safe Transaction Builder batch per fleet with any
 * non-`leave` ark action.
 *
 * Batch shape per fleet:
 *   1. unpause()                        — if the fleet is paused (reverts before
 *                                         pauseStartTime + minimumPauseTime, warned below)
 *   2. PAM.grantCuratorRole             — once, only if needed (sweepable flag flips /
 *                                         setArkDepositCap) and the Safe lacks it
 *   3. per sweep ark: setSweepableToken(true) → setNonSweepableToken(false) →
 *      Raft.socializeLosses(ark, [pool], receiver) → flags restored to prior state
 *   4. per removal ark: setArkDepositCap(ark, 0) (if cap > 0) then removeArk(ark)
 *   5. PAM.revokeCuratorRole            — if granted in 2
 *   6. pause()                          — if the fleet config sets `repauseAfter: true`
 *                                         (restarts the minimum pause window)
 *
 * Every action is re-validated against LIVE chain state — the config's numbers are the
 * operator's worksheet, not the source of truth.
 *
 * Non-interactive usage (all optional, prompts otherwise):
 *   BUMMER=true|false SAFE_ADDRESS=0x.. RECEIVER=0x.. FLEETS=0x..,0x.. YES=1 \
 *     NETWORK=mainnet pnpm gov:cleanup-fleets
 */

interface ArkWorkItem {
  entry: CleanupArkEntry
  liveTotalAssets: bigint
  liveDepositCap: bigint
  pool?: Address
  poolSymbol?: string
  poolBalance?: bigint
  isSweepable?: boolean
  isNonSweepable?: boolean
}

interface FleetWorkPlan {
  config: FleetCleanupConfig
  file: string
  livePaused: boolean
  unpauseNotBefore?: Date
  safeHasCurator: boolean
  sweeps: ArkWorkItem[]
  removals: ArkWorkItem[]
}

function fail(message: string): never {
  console.log(kleur.red(`❌ ${message}`))
  process.exit(1)
}

async function promptForAddressWithDefault(message: string, initial: Address): Promise<Address> {
  const { value } = await prompts({
    type: 'text',
    name: 'value',
    message,
    initial,
    validate: (val: string) => (/^0x[a-fA-F0-9]{40}$/.test(val.trim()) ? true : 'Invalid address'),
  })
  if (!value) {
    throw new Error('Address input is required')
  }
  return getAddress(value.trim())
}

async function main() {
  const network = hre.network.name
  const chainId = getChainId()
  console.log(kleur.blue('Network:'), kleur.cyan(`${network} (chainId ${chainId})`))

  const useBummerConfig =
    process.env.BUMMER !== undefined ? process.env.BUMMER === 'true' : await promptForConfigType()

  const config = getConfigByNetwork(
    network,
    { common: true, core: true, gov: true },
    useBummerConfig,
  ) as BaseConfig

  const raftAddress = getAddress(config.deployedContracts.core.raft.address)
  const pamAddress = getAddress(config.deployedContracts.gov.protocolAccessManager.address)
  const foundationAddress = getAddress(config.common.foundation)

  const publicClient = await hre.viem.getPublicClient()

  const safeAddress = process.env.SAFE_ADDRESS
    ? getAddress(process.env.SAFE_ADDRESS)
    : await promptForAddressWithDefault(
        'Governor Safe address (executes the batches):',
        foundationAddress,
      )
  const receiverAddress = process.env.RECEIVER
    ? getAddress(process.env.RECEIVER)
    : await promptForAddressWithDefault('Receiver of the swept tokens:', safeAddress)

  // ---- Load fleet configs ----
  const dir = cleanupConfigDir(network)
  if (!fs.existsSync(dir)) {
    fail(`No fleet-cleanup configs at ${dir} — run gov:cleanup-fleets:init first.`)
  }
  const fleetFilter = process.env.FLEETS
    ? new Set(process.env.FLEETS.split(',').map((a) => getAddress(a.trim())))
    : null

  const files = fs
    .readdirSync(dir)
    .filter((f) => f.endsWith('.json'))
    .map((f) => path.join(dir, f))

  const expectedConfigType = useBummerConfig ? 'test' : 'prod'
  const candidates: { file: string; config: FleetCleanupConfig }[] = []
  for (const file of files) {
    const parsed = JSON.parse(fs.readFileSync(file, 'utf8')) as FleetCleanupConfig
    if (fleetFilter && !fleetFilter.has(getAddress(parsed.fleetAddress))) continue
    if (parsed.chainId !== chainId) {
      fail(
        `${path.basename(file)} was generated for chainId ${parsed.chainId}, current is ${chainId}.`,
      )
    }
    if (parsed.configType !== expectedConfigType) {
      fail(
        `${path.basename(file)} was generated for configType "${parsed.configType}" but you selected "${expectedConfigType}" (BUMMER mismatch).`,
      )
    }
    for (const ark of parsed.arks) {
      if (!isCleanupAction(ark.action)) {
        fail(`${path.basename(file)}: ark ${ark.address} has invalid action "${ark.action}".`)
      }
      if (ark.isBufferArk && ark.action !== 'leave') {
        fail(`${path.basename(file)}: buffer ark ${ark.address} must have action "leave".`)
      }
    }
    const hasWork = parsed.arks.some((a) => a.action !== 'leave')
    if (hasWork) {
      candidates.push({ file, config: parsed })
    }
  }
  if (candidates.length === 0) {
    console.log(kleur.yellow('No fleet config has a non-"leave" action — nothing to do.'))
    return
  }

  // The whole plan hinges on the Safe holding GOVERNOR_ROLE — verify before building anything
  const governorRole = await publicClient.readContract({
    address: pamAddress,
    abi: pamViewAbi,
    functionName: 'GOVERNOR_ROLE',
  })
  const safeIsGovernor = await publicClient.readContract({
    address: pamAddress,
    abi: pamViewAbi,
    functionName: 'hasRole',
    args: [governorRole, safeAddress],
  })
  if (!safeIsGovernor) {
    fail(`${safeAddress} does not hold GOVERNOR_ROLE on ProtocolAccessManager ${pamAddress}.`)
  }
  console.log(kleur.green(`✓ ${safeAddress} holds GOVERNOR_ROLE`))

  // ---- Re-validate each fleet's plan against live chain state ----
  const plans: FleetWorkPlan[] = []
  for (const { file, config: fleetConfig } of candidates) {
    const fleetAddress = getAddress(fleetConfig.fleetAddress)
    console.log(kleur.blue(`\nValidating ${fleetConfig.fleetName} (${fleetAddress})…`))

    const [livePaused, pauseStartTime, minimumPauseTime, liveActiveArks, liveBufferArk] =
      await Promise.all([
        publicClient.readContract({ address: fleetAddress, abi: fleetAbi, functionName: 'paused' }),
        publicClient.readContract({
          address: fleetAddress,
          abi: fleetAbi,
          functionName: 'pauseStartTime',
        }),
        publicClient.readContract({
          address: fleetAddress,
          abi: fleetAbi,
          functionName: 'minimumPauseTime',
        }),
        publicClient.readContract({
          address: fleetAddress,
          abi: fleetAbi,
          functionName: 'getActiveArks',
        }),
        publicClient.readContract({
          address: fleetAddress,
          abi: fleetAbi,
          functionName: 'bufferArk',
        }),
      ])
    const activeArkSet = new Set(liveActiveArks.map((a) => getAddress(a)))

    const curatorRole = await publicClient.readContract({
      address: pamAddress,
      abi: pamViewAbi,
      functionName: 'generateRole',
      args: [CURATOR_ROLE_ENUM, fleetAddress],
    })
    const safeHasCurator = await publicClient.readContract({
      address: pamAddress,
      abi: pamViewAbi,
      functionName: 'hasRole',
      args: [curatorRole, safeAddress],
    })

    const plan: FleetWorkPlan = {
      config: fleetConfig,
      file,
      livePaused,
      unpauseNotBefore: livePaused
        ? new Date(Number(pauseStartTime + minimumPauseTime) * 1000)
        : undefined,
      safeHasCurator,
      sweeps: [],
      removals: [],
    }

    for (const entry of fleetConfig.arks.filter((a) => a.action !== 'leave')) {
      const arkAddress = getAddress(entry.address)
      if (arkAddress === getAddress(liveBufferArk)) {
        fail(`${entry.name} (${arkAddress}) is the live buffer ark of ${fleetAddress}.`)
      }
      if (!activeArkSet.has(arkAddress)) {
        fail(
          `${entry.name} (${arkAddress}) is not an active ark of fleet ${fleetAddress} (already removed?).`,
        )
      }

      const [liveTotalAssets, liveDepositCap, liveDetailsJson] = await Promise.all([
        publicClient.readContract({
          address: arkAddress,
          abi: arkAbi,
          functionName: 'totalAssets',
        }),
        publicClient.readContract({ address: arkAddress, abi: arkAbi, functionName: 'depositCap' }),
        publicClient.readContract({ address: arkAddress, abi: arkAbi, functionName: 'details' }),
      ])

      const item: ArkWorkItem = { entry, liveTotalAssets, liveDepositCap }
      const wantsSweep =
        entry.action === 'socializeLosses' || entry.action === 'socializeLossesAndRemove'
      const wantsRemoval =
        entry.action === 'socializeLossesAndRemove' || entry.action === 'removeArk'

      if (wantsSweep) {
        if (liveTotalAssets === 0n) {
          fail(
            `${entry.name} (${arkAddress}) has live totalAssets == 0 — nothing to socialize. ` +
              `Config is stale; use action "removeArk" instead if removal is intended.`,
          )
        }
        // totalAssets is backed by receipt/share tokens; the `pool` key of the details JSON is the
        // share token for vault-style arks. Verify that assumption holds before planning a sweep.
        const { pool } = parseDetailsJson(liveDetailsJson)
        if (!pool) {
          fail(
            `${entry.name} (${arkAddress}) has assets but details() has no usable "pool" address ` +
              `(${liveDetailsJson}) — handle manually.`,
          )
        }
        const poolBalance = await publicClient.readContract({
          address: pool,
          abi: erc20Abi,
          functionName: 'balanceOf',
          args: [arkAddress],
        })
        if (poolBalance === 0n) {
          fail(
            `${entry.name} (${arkAddress}) reports totalAssets ${liveTotalAssets} but holds no balance ` +
              `of details().pool token ${pool}. Sweeping would not zero totalAssets — handle manually.`,
          )
        }
        let poolSymbol = '???'
        try {
          poolSymbol = await publicClient.readContract({
            address: pool,
            abi: erc20Abi,
            functionName: 'symbol',
          })
        } catch {
          // non-standard token symbol — cosmetic only
        }
        const [isSweepable, isNonSweepable] = await Promise.all([
          publicClient.readContract({
            address: raftAddress,
            abi: raftViewAbi,
            functionName: 'sweepableTokens',
            args: [arkAddress, pool],
          }),
          publicClient.readContract({
            address: raftAddress,
            abi: raftViewAbi,
            functionName: 'nonSweepableTokens',
            args: [arkAddress, pool],
          }),
        ])
        item.pool = pool
        item.poolSymbol = poolSymbol
        item.poolBalance = poolBalance
        item.isSweepable = isSweepable
        item.isNonSweepable = isNonSweepable
        plan.sweeps.push(item)
      }

      if (wantsRemoval) {
        if (entry.action === 'removeArk' && liveTotalAssets > 0n) {
          fail(
            `${entry.name} (${arkAddress}) has live totalAssets ${liveTotalAssets} — plain "removeArk" ` +
              `would revert (FleetCommanderArkAssetsNotZero). Use "socializeLossesAndRemove".`,
          )
        }
        plan.removals.push(item)
      }
    }

    plans.push(plan)
  }

  // ---- Summary — these batches move user-fund backing out of fleets, make the numbers loud ----
  console.log(kleur.cyan().bold('\n================ Cleanup plan ================'))
  for (const plan of plans) {
    const { config: fc } = plan
    console.log(kleur.yellow(`\nFleet ${fc.fleetName} (${fc.fleetAddress})`))
    console.log(
      `  paused         : ${plan.livePaused}${plan.unpauseNotBefore ? ` (unpause executable after ${plan.unpauseNotBefore.toISOString()})` : ''}`,
    )
    console.log(`  repause after  : ${fc.repauseAfter}`)
    for (const s of plan.sweeps) {
      console.log(
        kleur.red(
          `  sweep          : ${s.entry.name} — ${formatAssets(s.liveTotalAssets, fc.assetDecimals, fc.assetSymbol)} ` +
            `backed by ${s.poolBalance} ${s.poolSymbol} (${s.pool}) → ${receiverAddress}`,
        ),
      )
      console.log(
        `                   raft flags: sweepable=${s.isSweepable} nonSweepable=${s.isNonSweepable}`,
      )
    }
    for (const r of plan.removals) {
      console.log(
        kleur.yellow(
          `  removeArk      : ${r.entry.name} (${r.entry.address}) — live cap ${r.liveDepositCap}, live assets ${r.liveTotalAssets}`,
        ),
      )
    }
  }
  const sweepCount = plans.reduce((n, p) => n + p.sweeps.length, 0)
  if (sweepCount > 0) {
    console.log(
      kleur
        .red()
        .bold(
          `\n⚠️  Sweeping removes the assets backing ${sweepCount} ark(s) from fleet accounting` +
            ` (fleet share price will drop accordingly — this socializes the losses).`,
        ),
    )
  }

  if (process.env.YES !== '1') {
    const { confirmed } = await prompts({
      type: 'confirm',
      name: 'confirmed',
      message: `Build ${plans.length} Safe transaction batch(es) for this plan?`,
      initial: false,
    })
    if (!confirmed) {
      console.log(kleur.red('Operation cancelled by user.'))
      return
    }
  }

  // ---- Assemble one batch per fleet ----
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-')
  const prefix = useBummerConfig ? 'test' : 'prod'
  const writtenFiles: string[] = []

  for (const plan of plans) {
    const { config: fc } = plan
    const fleetAddress = getAddress(fc.fleetAddress)
    const actions: BatchAction[] = []

    if (plan.livePaused) {
      actions.push({
        tx: buildTx(fleetAddress, writeAbis.unpause, []),
        summary: `FleetCommander(${fc.fleetName}).unpause() — not before ${plan.unpauseNotBefore?.toISOString()}`,
      })
    }

    const capRemovals = plan.removals.filter((r) => r.liveDepositCap > 0n)
    const needsCurator = plan.sweeps.some((s) => !s.isSweepable) || capRemovals.length > 0
    const grantCurator = needsCurator && !plan.safeHasCurator
    if (grantCurator) {
      actions.push({
        tx: buildTx(pamAddress, writeAbis.grantCuratorRole, [fleetAddress, safeAddress]),
        summary: `PAM.grantCuratorRole(${fc.fleetName}, safe) — temporary, for setSweepableToken/setArkDepositCap`,
      })
    }

    for (const s of plan.sweeps) {
      if (!s.isSweepable) {
        actions.push({
          tx: buildTx(raftAddress, writeAbis.setSweepableToken, [s.entry.address, s.pool!, true]),
          summary: `Raft.setSweepableToken(${s.entry.name}, ${s.poolSymbol}, true)`,
        })
      }
      if (s.isNonSweepable) {
        actions.push({
          tx: buildTx(raftAddress, writeAbis.setNonSweepableToken, [
            s.entry.address,
            s.pool!,
            false,
          ]),
          summary: `Raft.setNonSweepableToken(${s.entry.name}, ${s.poolSymbol}, false) — lift blacklist`,
        })
      }
      actions.push({
        tx: buildTx(raftAddress, writeAbis.socializeLosses, [
          s.entry.address,
          [s.pool!],
          receiverAddress,
        ]),
        summary: `Raft.socializeLosses(${s.entry.name}, [${s.poolSymbol}], ${receiverAddress}) — sweeps ${s.poolBalance} shares`,
      })
      // restore the exact prior flag state
      if (s.isNonSweepable) {
        actions.push({
          tx: buildTx(raftAddress, writeAbis.setNonSweepableToken, [
            s.entry.address,
            s.pool!,
            true,
          ]),
          summary: `Raft.setNonSweepableToken(${s.entry.name}, ${s.poolSymbol}, true) — restore blacklist`,
        })
      }
      if (!s.isSweepable) {
        actions.push({
          tx: buildTx(raftAddress, writeAbis.setSweepableToken, [s.entry.address, s.pool!, false]),
          summary: `Raft.setSweepableToken(${s.entry.name}, ${s.poolSymbol}, false) — restore whitelist`,
        })
      }
    }

    for (const r of capRemovals) {
      actions.push({
        tx: buildTx(fleetAddress, writeAbis.setArkDepositCap, [r.entry.address, 0n]),
        summary: `FleetCommander.setArkDepositCap(${r.entry.name}, 0)`,
      })
    }
    for (const r of plan.removals) {
      actions.push({
        tx: buildTx(fleetAddress, writeAbis.removeArk, [r.entry.address]),
        summary: `FleetCommander(${fc.fleetName}).removeArk(${r.entry.name})`,
      })
    }

    if (grantCurator) {
      actions.push({
        tx: buildTx(pamAddress, writeAbis.revokeCuratorRole, [fleetAddress, safeAddress]),
        summary: `PAM.revokeCuratorRole(${fc.fleetName}, safe) — cleanup`,
      })
    }
    if (fc.repauseAfter) {
      actions.push({
        tx: buildTx(fleetAddress, writeAbis.pause, []),
        summary: `FleetCommander(${fc.fleetName}).pause() — restore paused state (restarts the minimum pause window)`,
      })
    }

    printActions(`Batch — ${fc.fleetName}`, actions)

    const sweepDescriptions = plan.sweeps.map(
      (s) => `socialize ${s.entry.name} (${s.entry.address}) pool ${s.pool} → ${receiverAddress}`,
    )
    const removalDescriptions = plan.removals.map(
      (r) => `remove ${r.entry.name} (${r.entry.address})`,
    )
    const outFile = path.join(
      proposalsDir(),
      `${prefix}_fleet_cleanup_${sanitizeFleetName(fc.fleetName)}_${network}_${timestamp}.json`,
    )
    writtenFiles.push(
      writeSafeBatch(
        actions,
        {
          name: `Fleet cleanup — ${fc.fleetName}`,
          description:
            [...sweepDescriptions, ...removalDescriptions].join('; ') +
            (plan.livePaused && plan.unpauseNotBefore
              ? `. NOT EXECUTABLE BEFORE ${plan.unpauseNotBefore.toISOString()} (unpause gated by minimum pause time).`
              : '') +
            (fc.repauseAfter ? ' Fleet is re-paused at the end of the batch.' : ''),
          safeAddress,
          chainId,
        },
        outFile,
      ),
    )
  }

  console.log(kleur.green().bold('\n✅ Safe transaction batches written:'))
  for (const f of writtenFiles) {
    console.log(kleur.green(`   ${f}`))
  }
  console.log(
    kleur.cyan(
      '\nImport each file in the Safe web UI: Apps → Transaction Builder → drag & drop the JSON, then review the decoded actions and collect signatures.',
    ),
  )
  const futureUnpauses = plans.filter(
    (p) => p.livePaused && p.unpauseNotBefore && p.unpauseNotBefore.getTime() > Date.now(),
  )
  for (const p of futureUnpauses) {
    console.log(
      kleur
        .red()
        .bold(
          `⚠️  ${p.config.fleetName}: batch reverts if executed before ${p.unpauseNotBefore!.toISOString()} (minimum pause time).`,
        ),
    )
  }
  console.log(
    kleur.gray(
      'After execution, remember to update the fleet deployment JSON (deployments/fleets/), curation arks.json, and regenerate the fleet-cleanup config (FORCE=1) by hand.',
    ),
  )
}

main().catch((error) => {
  console.error(kleur.red().bold('An error occurred:'), error)
  process.exit(1)
})
