// SPDX-License-Identifier: BUSL-1.1
pragma solidity 0.8.28;

import "../Ark.sol";

/**
 * @title WisdomTreeArk
 * @notice Ark contract for managing token supply by sending boarded assets to a specific wallet.
 * @dev Implements strategy for depositing tokens to an external wallet and tracking the balance manually.
 *      Disembarking requires the assets to be manually returned to this contract beforehand.
 */
contract WisdomTreeArk is Ark {
    using SafeERC20 for IERC20;

    /*//////////////////////////////////////////////////////////////
                                ERRORS
    //////////////////////////////////////////////////////////////*/

    error InvalidTargetWallet();
    error InsufficientDepositedAssets();
    error InsufficientFundsInArk();

    /*//////////////////////////////////////////////////////////////
                            STATE VARIABLES
    //////////////////////////////////////////////////////////////*/

    /// @notice The wallet address where boarded assets are sent
    address public immutable targetWallet;

    /// @notice The total amount of assets currently considered deposited in the target wallet
    uint256 public depositedAssets;

    /*//////////////////////////////////////////////////////////////
                                CONSTRUCTOR
    //////////////////////////////////////////////////////////////*/
    /**
     * @notice Constructor to set up the WisdomTreeArk
     * @param _targetWallet The address of the wallet to receive assets
     * @param _params ArkParams struct containing necessary parameters for Ark initialization
     */
    constructor(address _targetWallet, ArkParams memory _params) Ark(_params) {
        if (_targetWallet == address(0)) {
            revert InvalidTargetWallet();
        }
        targetWallet = _targetWallet;
    }

    /**
     * @inheritdoc IArk
     * @notice Returns the total assets managed by this Ark
     * @return assets The total balance of assets tracked as deposited
     */
    function totalAssets() public view override returns (uint256 assets) {
        assets = depositedAssets;
    }

    /*//////////////////////////////////////////////////////////////
                                INTERNAL FUNCTIONS
    //////////////////////////////////////////////////////////////*/

    /**
     * @notice Internal function to get the total assets that are withdrawable
     * @dev WisdomTreeArk is considered withdrawable based on tracked deposits,
     *      but actual withdrawal depends on manual funding of this contract.
     */
    function _withdrawableTotalAssets()
        internal
        view
        override
        returns (uint256 withdrawableAssets)
    {
        withdrawableAssets = depositedAssets;
    }

    /**
     * @notice Deposits assets by sending them to the target wallet
     * @param amount The amount of assets to deposit
     * @param /// data Additional data (unused in this implementation)
     */
    function _board(uint256 amount, bytes calldata) internal override {
        depositedAssets += amount;
        config.asset.safeTransfer(targetWallet, amount);
    }

    /**
     * @notice Withdraws assets from the Ark
     * @dev Assumes assets have been manually transferred back to this contract.
     *      Updates the tracked deposited amount.
     * @param amount The amount of assets to withdraw
     * @param /// data Additional data (unused in this implementation)
     */
    function _disembark(uint256 amount, bytes calldata) internal override {
        if (amount > depositedAssets) {
            revert InsufficientDepositedAssets();
        }
        if (config.asset.balanceOf(address(this)) < amount) {
            revert InsufficientFundsInArk();
        }
        depositedAssets -= amount;
        // The base Ark.disembark function will handle the transfer to the user
        // from this contract's balance. We just need to ensure the accounting is correct
        // and that this contract HAS the tokens (checked by safeTransfer in base).
    }

    /**
     * @notice Internal function for harvesting rewards
     * @dev No rewards are generated by this Ark strategy
     * @param /// data Additional data (unused in this implementation)
     * @return rewardTokens Empty array
     * @return rewardAmounts Empty array
     */
    function _harvest(
        bytes calldata
    )
        internal
        virtual
        override
        returns (address[] memory rewardTokens, uint256[] memory rewardAmounts)
    {
        rewardTokens = new address[](0);
        rewardAmounts = new uint256[](0);
    }

    /**
     * @notice Validates the board data
     * @dev This Ark does not require any validation for board data
     * @param /// data Additional data to validate (unused in this implementation)
     */
    function _validateBoardData(bytes calldata) internal override {}

    /**
     * @notice Validates the disembark data
     * @dev This Ark does not require any validation for disembark data
     * @param /// data Additional data to validate (unused in this implementation)
     */
    function _validateDisembarkData(bytes calldata) internal override {}
}
