// SPDX-License-Identifier: BUSL-1.1
pragma solidity 0.8.28;

/**
 * @title BridgeTypes
 * @notice Library of types used by the bridge contracts
 */
library BridgeTypes {
    /**
     * @notice Status of a cross-chain transfer
     */
    enum OperationStatus {
        SENT, // Operation has been sent to the destination chain
        FAILED // Operation has failed
    }

    /**
     * @notice Generic adapter options structure for cross-chain operations
     */
    struct AdapterParams {
        uint64 gasLimit; // Gas limit for execution on destination chain
        uint32 calldataSize; // Size of expected return calldata (for read operations)
        uint128 msgValue; // Native value to forward (for operations requiring value)
        bytes options; // Additional adapter-specific parameters
    }

    /**
     * @notice Bridge options structure
     */
    struct BridgeOptions {
        address specifiedAdapter; // Required specific adapter to use (address(0) will revert)
        AdapterParams adapterParams; // Generic adapter options
    }

    // Enum for operation types
    enum OperationType {
        MESSAGE,
        READ_STATE,
        TRANSFER_ASSET
    }

    /**
     * @notice Parameters for executeTransferAssets
     */
    struct ExecuteTransferParams {
        uint16 destinationChainId;
        address asset;
        uint256 amount;
        address recipient;
        address originator;
        address keeper; // Add keeper field for refunds
        BridgeOptions options;
    }

    /**
     * @notice Parameters for executeReadState
     */
    struct ExecuteReadStateParams {
        uint16 destinationChainId;
        address destinationContract;
        bytes4 selector;
        bytes readParams;
        address originator;
        address keeper; // Add keeper field for refunds
        BridgeOptions options;
    }

    /**
     * @notice Parameters for executeSendMessage
     */
    struct ExecuteSendMessageParams {
        uint16 destinationChainId;
        address recipient;
        bytes message;
        address originator;
        address keeper; // Add keeper field for refunds
        BridgeOptions options;
    }

    struct DeliverPayload {
        bytes32 operationId; // cross-chain operation ID
        address originator; // original msg.sender on the source chain
        address sourceAsset; // token the user supplied on the source chain
    }

    /**
     * @notice Layout of the asset transfer message for transfer enabled adapters.
     *
     * recipient      – FleetProxy on the destination chain
     * asset          – ERC-20 on the *source* chain being bridged
     * amount         – Amount that left the source chain
     * sourceChainId  – EVM chain id where the transfer originated
     * operationId    – ID generated by BridgeRouter for tracking
     * originator     – Original msg.sender on the source chain
     */
    struct AssetTransferMessage {
        address recipient;
        address asset;
        uint256 amount;
        uint256 sourceChainId;
        bytes32 operationId;
        address originator;
    }

    /**
     * @notice Generic wrapper for a cross-chain state–read response
     * @dev Keeps result bytes in a typed container so every contract
     *      that consumes the response can simply:
     *          BridgeTypes.ReadResponse memory r =
     *              abi.decode(resultData, (BridgeTypes.ReadResponse));
     *      and then decode `r.data` to whatever concrete type it expects.
     */
    struct ReadResponse {
        bytes data; // ABI-encoded return data of the read call
    }
}
