// SPDX-License-Identifier: BUSL-1.1
pragma solidity 0.8.28;

import {ERC20Mock} from "@openzeppelin/contracts/mocks/token/ERC20Mock.sol";

import {BridgeTypes} from "../../../src/libraries/BridgeTypes.sol";
import {IBridgeAdapter} from "../../../src/interfaces/IBridgeAdapter.sol";
import {MockOFT} from "../../mocks/MockOFT.sol";
import {LayerZeroAdapter} from "../../../src/adapters/LayerZeroAdapter.sol";
import {LayerZeroAdapterTestHelper} from "../../helpers/LayerZeroAdapterTestHelper.sol";
import {LayerZeroAdapterSetupTest} from "./LayerZeroAdapter.setup.t.sol";
import {BridgeOptionsTestHelper} from "../../helpers/BridgeOptionsTestHelper.sol";
import {TransferHelpers} from "../../helpers/TransferHelpers.t.sol";

/**
 * @title LayerZeroAdapter Protocol Token Fee Tests
 * @notice Tests for protocol token fee payment functionality in LayerZeroAdapter
 */
contract LayerZeroAdapterProtocolTokenFeeTest is
    LayerZeroAdapterSetupTest,
    TransferHelpers
{
    using BridgeOptionsTestHelper for address;

    ERC20Mock public protocolFeeToken;
    MockOFT public mockOFT;
    uint256 public constant PROTOCOL_FEE_AMOUNT = 1000e18; // 1000 tokens (matches mock)

    event ProtocolFeeCollected(
        bytes32 indexed operationId,
        address indexed payer,
        address indexed token,
        uint256 tokenFee
    );

    event ProtocolFeeSpent(
        bytes32 indexed operationId,
        address indexed token,
        uint256 tokenFee
    );

    function setUp() public override {
        super.setUp();

        // Deploy a mock protocol fee token
        protocolFeeToken = new ERC20Mock();

        // Deploy a mock OFT for testing
        mockOFT = new MockOFT("Mock OFT", "MOFT", address(tokenA), lzEndpointA);

        // Configure mock OFT fees
        mockOFT.setMockFees(0.01 ether, PROTOCOL_FEE_AMOUNT);

        // Set fee token on mock OFT for ERC-7802 testing
        mockOFT.setFeeToken(address(protocolFeeToken));

        // Configure protocol fee token on adapter
        vm.prank(governor);
        adapterA.setProtocolFeeToken(address(protocolFeeToken));

        // Set up OFT mapping for the test token
        adapterA.setOftForTokenTest(address(tokenA), address(mockOFT));

        // Mint protocol tokens to user
        protocolFeeToken.mint(user, 10000e18);

        // User (keeper) approves adapter to spend protocol tokens
        vm.prank(user);
        protocolFeeToken.approve(address(adapterA), type(uint256).max);

        // User approves router to spend test tokens (already minted in parent setup)
        vm.prank(user);
        tokenA.approve(address(routerA), type(uint256).max);

        // Fund user with ETH for native payment tests
        vm.deal(user, 10 ether);

        // Fund adapter with ETH for refunds
        vm.deal(address(adapterA), 100 ether);
    }

    /*//////////////////////////////////////////////////////////////
                        TOKEN PAYMENT SUCCESS TESTS
    //////////////////////////////////////////////////////////////*/

    function testTransferAssetWithProtocolTokenPayment() public {
        useNetworkA();

        uint256 transferAmount = 1000e18;

        // Create bridge options with token payment
        BridgeTypes.BridgeOptions memory options = BridgeTypes.BridgeOptions({
            specifiedAdapter: address(adapterA),
            gasLimit: 500000,
            calldataSize: 0,
            msgValue: 0,
            feeTokenAmount: PROTOCOL_FEE_AMOUNT,
            payInProtocolToken: true,
            options: bytes("")
        });

        // Create transfer parameters
        BridgeTypes.ExecuteTransferParams memory params = BridgeTypes
            .ExecuteTransferParams({
                originator: user,
                asset: address(tokenA),
                amount: transferAmount,
                destinationChainId: CHAIN_ID_B,
                target: address(adapterB),
                message: "",
                refundAddress: user
            });

        // Record initial balances
        uint256 initialProtocolTokenBalance = protocolFeeToken.balanceOf(user);
        uint256 initialTokenBalance = tokenA.balanceOf(user);

        // Note: We don't check events in this test since operationId is generated by router
        // The important part is that the balances are correct

        // Execute transfer with protocol token fee
        vm.prank(user);
        routerA.executeTransferAssets{value: 0}(params, options);

        // Verify protocol token was deducted from user
        assertEq(
            protocolFeeToken.balanceOf(user),
            initialProtocolTokenBalance - PROTOCOL_FEE_AMOUNT,
            "Protocol token should be deducted from user"
        );

        // Verify test token was transferred
        assertEq(
            tokenA.balanceOf(user),
            initialTokenBalance - transferAmount,
            "Test token should be transferred"
        );
    }

    function testTransferAssetWithNativePaymentFallback() public {
        useNetworkA();

        uint256 transferAmount = 1000e18;
        uint256 nativeFee = 0.01 ether; // Use exact amount required

        // Create bridge options with native payment (protocol token not set)
        BridgeTypes.BridgeOptions memory options = BridgeTypes.BridgeOptions({
            specifiedAdapter: address(adapterA),
            gasLimit: 500000,
            calldataSize: 0,
            msgValue: uint128(nativeFee),
            feeTokenAmount: 0,
            payInProtocolToken: false,
            options: bytes("")
        });

        // Create transfer parameters
        BridgeTypes.ExecuteTransferParams memory params = BridgeTypes
            .ExecuteTransferParams({
                originator: user,
                asset: address(tokenA),
                amount: transferAmount,
                destinationChainId: CHAIN_ID_B,
                target: address(adapterB),
                message: "",
                refundAddress: user
            });

        // Record initial balances
        uint256 initialTokenBalance = tokenA.balanceOf(user);

        // Execute transfer with native fee
        vm.prank(user);
        routerA.executeTransferAssets{value: nativeFee}(params, options);

        // Verify test token was transferred
        assertEq(
            tokenA.balanceOf(user),
            initialTokenBalance - transferAmount,
            "Test token should be transferred"
        );
    }

    function testTransferAssetWithNativePaymentWhenProtocolTokenNotSet()
        public
    {
        useNetworkA();

        // Temporarily unset protocol token to test fallback behavior
        vm.startPrank(governor);
        adapterA.setProtocolFeeToken(address(0)); // Unset protocol token
        vm.stopPrank();

        uint256 transferAmount = 1000e18;
        uint256 nativeFee = 0.01 ether;

        // Create bridge options with token payment but no protocol token set
        BridgeTypes.BridgeOptions memory options = BridgeTypes.BridgeOptions({
            specifiedAdapter: address(adapterA), // Use the main adapter, not the new one
            gasLimit: 500000,
            calldataSize: 0,
            msgValue: uint128(nativeFee),
            feeTokenAmount: PROTOCOL_FEE_AMOUNT,
            payInProtocolToken: true, // Try to pay in token
            options: bytes("")
        });

        // Create transfer parameters
        BridgeTypes.ExecuteTransferParams memory params = BridgeTypes
            .ExecuteTransferParams({
                originator: user,
                asset: address(tokenA),
                amount: transferAmount,
                destinationChainId: CHAIN_ID_B,
                target: address(adapterB),
                message: "",
                refundAddress: user
            });

        // Should fall back to native fee payment
        vm.prank(user);
        routerA.executeTransferAssets{value: nativeFee}(params, options);

        // Verify test token was transferred
        assertEq(
            tokenA.balanceOf(user),
            9000e18, // 10000 - 1000
            "Test token should be transferred"
        );
    }

    /*//////////////////////////////////////////////////////////////
                        ESTIMATION TESTS
    //////////////////////////////////////////////////////////////*/

    function testEstimateTransferAssetsWithTokenPayment() public {
        useNetworkA();

        // Create bridge options with token payment
        BridgeTypes.BridgeOptions memory options = BridgeTypes.BridgeOptions({
            specifiedAdapter: address(adapterA),
            gasLimit: 500000,
            calldataSize: 0,
            msgValue: 0,
            feeTokenAmount: PROTOCOL_FEE_AMOUNT,
            payInProtocolToken: true,
            options: bytes("")
        });

        // Create transfer parameters
        BridgeTypes.ExecuteTransferParams memory params = BridgeTypes
            .ExecuteTransferParams({
                originator: user,
                asset: address(tokenA),
                amount: 1000e18,
                destinationChainId: CHAIN_ID_B,
                target: address(adapterB),
                message: "",
                refundAddress: user
            });

        // Estimate fees with token payment
        (uint256 nativeFee, uint256 tokenFee) = adapterA.estimateTransferAssets(
            params,
            options
        );

        // When paying in token, native fee should be 0 and token fee should be set
        assertEq(nativeFee, 0, "Native fee should be 0 when paying in token");
        assertGt(tokenFee, 0, "Token fee should be greater than 0");
    }

    function testEstimateTransferAssetsWithNativePayment() public {
        useNetworkA();

        // Create bridge options with native payment
        BridgeTypes.BridgeOptions memory options = BridgeTypes.BridgeOptions({
            specifiedAdapter: address(adapterA),
            gasLimit: 500000,
            calldataSize: 0,
            msgValue: 0,
            feeTokenAmount: 0,
            payInProtocolToken: false,
            options: bytes("")
        });

        // Create transfer parameters
        BridgeTypes.ExecuteTransferParams memory params = BridgeTypes
            .ExecuteTransferParams({
                originator: user,
                asset: address(tokenA),
                amount: 1000e18,
                destinationChainId: CHAIN_ID_B,
                target: address(adapterB),
                message: "",
                refundAddress: user
            });

        // Estimate fees with native payment
        (uint256 nativeFee, uint256 tokenFee) = adapterA.estimateTransferAssets(
            params,
            options
        );

        // When paying in native, native fee should be set and token fee should be 0
        assertGt(nativeFee, 0, "Native fee should be greater than 0");
        assertEq(tokenFee, 0, "Token fee should be 0 when paying in native");
    }

    /*//////////////////////////////////////////////////////////////
                        ERROR CASE TESTS
    //////////////////////////////////////////////////////////////*/

    function testTransferAssetRevertsWhenInsufficientProtocolTokens() public {
        useNetworkA();

        uint256 transferAmount = 1000e18;

        // Reduce user's protocol token balance to less than required
        vm.prank(user);
        protocolFeeToken.transfer(address(0xdead), 9500e18); // Leave only 500e18 tokens

        // Create bridge options with correct token payment amount
        BridgeTypes.BridgeOptions memory options = BridgeTypes.BridgeOptions({
            specifiedAdapter: address(adapterA),
            gasLimit: 500000,
            calldataSize: 0,
            msgValue: 0,
            feeTokenAmount: PROTOCOL_FEE_AMOUNT, // Correct amount (1000e18)
            payInProtocolToken: true,
            options: bytes("")
        });

        // Create transfer parameters
        BridgeTypes.ExecuteTransferParams memory params = BridgeTypes
            .ExecuteTransferParams({
                originator: user,
                asset: address(tokenA),
                amount: transferAmount,
                destinationChainId: CHAIN_ID_B,
                target: address(adapterB),
                message: "",
                refundAddress: user
            });

        // Should revert due to insufficient protocol tokens
        vm.expectRevert();
        vm.prank(user);
        routerA.executeTransferAssets{value: 0}(params, options);
    }

    function testTransferAssetRevertsWhenWrongFeeTokenAmount() public {
        useNetworkA();

        uint256 transferAmount = 1000e18;

        // Create bridge options with wrong fee token amount
        BridgeTypes.BridgeOptions memory options = BridgeTypes.BridgeOptions({
            specifiedAdapter: address(adapterA),
            gasLimit: 500000,
            calldataSize: 0,
            msgValue: 0,
            feeTokenAmount: PROTOCOL_FEE_AMOUNT / 2, // Less than required
            payInProtocolToken: true,
            options: bytes("")
        });

        // Create transfer parameters
        BridgeTypes.ExecuteTransferParams memory params = BridgeTypes
            .ExecuteTransferParams({
                originator: user,
                asset: address(tokenA),
                amount: transferAmount,
                destinationChainId: CHAIN_ID_B,
                target: address(adapterB),
                message: "",
                refundAddress: user
            });

        // Should revert due to insufficient fee token amount
        vm.expectRevert();
        vm.prank(user);
        routerA.executeTransferAssets{value: 0}(params, options);
    }

    function testTransferAssetRevertsWhenNativeFeeNotZeroInTokenMode() public {
        useNetworkA();

        uint256 transferAmount = 1000e18;

        // Create bridge options with token payment
        BridgeTypes.BridgeOptions memory options = BridgeTypes.BridgeOptions({
            specifiedAdapter: address(adapterA),
            gasLimit: 500000,
            calldataSize: 0,
            msgValue: 0.01 ether, // Provide native value when paying in token
            feeTokenAmount: PROTOCOL_FEE_AMOUNT,
            payInProtocolToken: true,
            options: bytes("")
        });

        // Create transfer parameters
        BridgeTypes.ExecuteTransferParams memory params = BridgeTypes
            .ExecuteTransferParams({
                originator: user,
                asset: address(tokenA),
                amount: transferAmount,
                destinationChainId: CHAIN_ID_B,
                target: address(adapterB),
                message: "",
                refundAddress: user
            });

        // Should revert if native fee is not zero when paying in token
        // The adapter should validate that when payInProtocolToken is true, native fee should be 0
        vm.expectRevert();
        vm.prank(user);
        routerA.executeTransferAssets{value: 0.01 ether}(params, options);
    }

    function testTransferAssetRevertsWhenFeeAmountMismatch() public {
        useNetworkA();

        uint256 transferAmount = 1000e18;

        // Create bridge options with wrong fee token amount (too low)
        BridgeTypes.BridgeOptions memory options = BridgeTypes.BridgeOptions({
            specifiedAdapter: address(adapterA),
            gasLimit: 500000,
            calldataSize: 0,
            msgValue: 0,
            feeTokenAmount: PROTOCOL_FEE_AMOUNT / 2, // Half of required amount (500e18)
            payInProtocolToken: true,
            options: bytes("")
        });

        // Create transfer parameters
        BridgeTypes.ExecuteTransferParams memory params = BridgeTypes
            .ExecuteTransferParams({
                originator: user,
                asset: address(tokenA),
                amount: transferAmount,
                destinationChainId: CHAIN_ID_B,
                target: address(adapterB),
                message: "",
                refundAddress: user
            });

        // Should revert due to fee amount mismatch
        vm.expectRevert();
        vm.prank(user);
        routerA.executeTransferAssets{value: 0}(params, options);
    }

    /*//////////////////////////////////////////////////////////////
                        ADDITIONAL VALIDATION TESTS
    //////////////////////////////////////////////////////////////*/

    function testTransferAssetRevertsWhenNativeFeeNotZeroInTokenModeDuplicate()
        public
    {
        useNetworkA();

        uint256 transferAmount = 1000e18;

        // Create bridge options with token payment but native value provided
        BridgeTypes.BridgeOptions memory options = BridgeTypes.BridgeOptions({
            specifiedAdapter: address(adapterA),
            gasLimit: 500000,
            calldataSize: 0,
            msgValue: 0.01 ether, // Native value when paying in token
            feeTokenAmount: PROTOCOL_FEE_AMOUNT,
            payInProtocolToken: true,
            options: bytes("")
        });

        // Create transfer parameters
        BridgeTypes.ExecuteTransferParams memory params = BridgeTypes
            .ExecuteTransferParams({
                originator: user,
                asset: address(tokenA),
                amount: transferAmount,
                destinationChainId: CHAIN_ID_B,
                target: address(adapterB),
                message: "",
                refundAddress: user
            });

        // Should revert due to invalid payment mode (protocol token + native value)
        vm.expectRevert();
        vm.prank(user);
        routerA.executeTransferAssets{value: 0.01 ether}(params, options);
    }

    function testTransferAssetRevertsWhenInsufficientNativeFee() public {
        useNetworkA();

        uint256 transferAmount = 1000e18;
        uint256 providedNativeFee = 0.005 ether; // Less than required

        // Create bridge options with native payment
        BridgeTypes.BridgeOptions memory options = BridgeTypes.BridgeOptions({
            specifiedAdapter: address(adapterA),
            gasLimit: 500000,
            calldataSize: 0,
            msgValue: uint128(providedNativeFee),
            feeTokenAmount: 0,
            payInProtocolToken: false,
            options: bytes("")
        });

        // Create transfer parameters
        BridgeTypes.ExecuteTransferParams memory params = BridgeTypes
            .ExecuteTransferParams({
                originator: user,
                asset: address(tokenA),
                amount: transferAmount,
                destinationChainId: CHAIN_ID_B,
                target: address(adapterB),
                message: "",
                refundAddress: user
            });

        // Should revert due to insufficient native fee
        vm.expectRevert();
        vm.prank(user);
        routerA.executeTransferAssets{value: providedNativeFee}(
            params,
            options
        );
    }

    function testTransferAssetRevertsWhenTokenFeeMismatch() public {
        useNetworkA();

        uint256 transferAmount = 1000e18;
        uint256 wrongTokenFee = PROTOCOL_FEE_AMOUNT * 2; // Double the required amount

        // Create bridge options with wrong token fee amount
        BridgeTypes.BridgeOptions memory options = BridgeTypes.BridgeOptions({
            specifiedAdapter: address(adapterA),
            gasLimit: 500000,
            calldataSize: 0,
            msgValue: 0,
            feeTokenAmount: wrongTokenFee,
            payInProtocolToken: true,
            options: bytes("")
        });

        // Create transfer parameters
        BridgeTypes.ExecuteTransferParams memory params = BridgeTypes
            .ExecuteTransferParams({
                originator: user,
                asset: address(tokenA),
                amount: transferAmount,
                destinationChainId: CHAIN_ID_B,
                target: address(adapterB),
                message: "",
                refundAddress: user
            });

        // Should revert due to token fee mismatch
        vm.expectRevert();
        vm.prank(user);
        routerA.executeTransferAssets{value: 0}(params, options);
    }

    function testTransferAssetRevertsWhenNativeFeeNotZeroInTokenPayment()
        public
    {
        useNetworkA();

        uint256 transferAmount = 1000e18;

        // Mock the OFT to return a non-zero native fee when paying in token
        mockOFT.setMockFees(0.01 ether, PROTOCOL_FEE_AMOUNT); // Native fee > 0
        mockOFT.setForceNativeFeeInTokenMode(true); // Force non-zero native fee in token mode

        // Create bridge options with token payment
        BridgeTypes.BridgeOptions memory options = BridgeTypes.BridgeOptions({
            specifiedAdapter: address(adapterA),
            gasLimit: 500000,
            calldataSize: 0,
            msgValue: 0,
            feeTokenAmount: PROTOCOL_FEE_AMOUNT,
            payInProtocolToken: true,
            options: bytes("")
        });

        // Create transfer parameters
        BridgeTypes.ExecuteTransferParams memory params = BridgeTypes
            .ExecuteTransferParams({
                originator: user,
                asset: address(tokenA),
                amount: transferAmount,
                destinationChainId: CHAIN_ID_B,
                target: address(adapterB),
                message: "",
                refundAddress: user
            });

        // Should revert when native fee is not zero in token payment mode
        vm.expectRevert(
            abi.encodeWithSelector(
                IBridgeAdapter.InsufficientFee.selector,
                0,
                0.01 ether
            )
        );
        vm.prank(user);
        routerA.executeTransferAssets{value: 0}(params, options);
    }

    /*//////////////////////////////////////////////////////////////
                        HELPER FUNCTIONS
    //////////////////////////////////////////////////////////////*/

    function _toArray16(uint16 value) internal pure returns (uint16[] memory) {
        uint16[] memory array = new uint16[](1);
        array[0] = value;
        return array;
    }

    function _toArray32(uint32 value) internal pure returns (uint32[] memory) {
        uint32[] memory array = new uint32[](1);
        array[0] = value;
        return array;
    }
}
