[profile.default]
src = "src"
out = "out"
libs = ["node_modules"]
remappings = []
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 10000

[profile.test]
src = "src"
test = "test"
out = "out"
libs = ["node_modules"]
solc_version = "0.8.28"
verbosity = 3
# Disable IR-based code generation
via_ir = false
optimizer = true
optimizer_runs = 200

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "remove"
quote_style = "double"
tab_width = 4
wrap_comments = true
sort_imports = true
contract_new_lines = true

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
base = "${BASE_RPC_URL}"
sonic = "${SONIC_RPC_URL}"

[etherscan]
mainnet = { key = "${API_KEY_ETHERSCAN}" }
arbitrum = { key = "${API_KEY_ARBISCAN}" }
base = { key = "${API_KEY_BASESCAN}" }
sonic = { key = "${API_KEY_SONICSCAN}" }
