// SPDX-License-Identifier: BUSL-1.1
pragma solidity 0.8.28;

import "@summerfi/price-solidity/contracts/PriceUtils.sol";

import "../../interfaces/extensions/ERC4626MultiTokenWrapper/IERC4626MultiTokenWrapper.sol";

import "./IRoundsVaultBaseEnums.sol";
import "./IRoundsVaultBaseErrors.sol";
import "./IRoundsVaultBaseEvents.sol";

/**
    @title IRoundsVaultBase

    @notice Public interface for a vault that batches user activity into discrete rounds and only
    moves funds into/out of a target ERC-4626 vault when the keeper closes and settles each round.
    Lets users interact at any block even when the target vault settles asynchronously (e.g. T+0/T+1
    against an off-chain NAV strike).

    @notice At deposit time, a user receives an ERC-1155 receipt whose id is the current round number
    and whose amount equals the deposited asset amount (1:1, same decimals). Receipts for the current
    open round can be redeemed back for the deposit asset at any time. Receipts for past rounds can
    only be exchanged once the keeper settles the round; the exchange asset is then released at the
    rate snapshotted from the actual settlement trade.

    @notice The "exchange asset" depends on the vault flavor (see `IRoundsVaultBaseEnums.BaseVaultType`):
    - `Input`: deposit asset is the target vault's underlying; exchange asset is target vault shares.
    - `Output`: deposit asset is target vault shares; exchange asset is the target vault's underlying.

    @notice For each settled round the contract stores a per-round exchange rate (a `Price` struct),
    so the price each user receives is the price of the round they participated in, not the spot price
    at redemption time.

    @author Roberto Cano <robercano>
 */
interface IRoundsVaultBase is IERC4626MultiTokenWrapper {
    // PUBLIC FUNCTIONS

    /**
     * @notice The vault flavor configured at construction: `Input` or `Output`.
     * @dev Exposed via the public-immutable getter generated by `RoundsVaultBase.VAULT_TYPE`.
     * @return The configured `BaseVaultType` for this vault instance.
     */
    function VAULT_TYPE()
        external
        view
        returns (IRoundsVaultBaseEnums.BaseVaultType);

    /**
     * @notice Closes the current round and opens the next one. Freezes the receipt supply of the
     *         closing round as the exact settlement liability and moves it to `InSettlement`.
     * @dev No funds move here; settlement is a separate keeper call (`setRoundSettled`). Reverts if
     *      the current round is not in `Opened` state. Restricted to the keeper role.
     */
    function nextRound() external;

    /**
     * @notice Burns receipts from a past, settled round and pays out the exchange asset at the rate
     *         snapshotted for that round.
     * @dev The exchange asset is target vault shares for `Input` flavor and the target vault's
     *      underlying for `Output` flavor. Reverts if the round is the current open round or if the
     *      round is not in `Settled` state. Caller must be the owner or be approved for all by the
     *      owner. Caller, owner and receiver must all be whitelisted on the target vault context.
     * @param id The round id whose receipts are being burned
     * @param amount The amount of receipts to burn
     * @param receiver The address that receives the exchange asset
     * @param owner The address whose receipts are burned, in case the caller is not the owner
     * @return The amount of exchange asset transferred to `receiver`
     */
    function redeemExchangeAsset(
        uint256 id,
        uint256 amount,
        address receiver,
        address owner
    ) external returns (uint256);

    /**
     * @notice Batch variant of `redeemExchangeAsset`. Burns receipts from several past settled rounds
     *         in one call and pays out the sum of their per-round exchange amounts.
     * @dev Each id must be a past round in `Settled` state. The arrays must be the same length.
     *      Caller, owner and receiver must all be whitelisted on the target vault context.
     * @param ids The round ids whose receipts are being burned
     * @param amounts The amount of receipts to burn per round id (must match `ids` length)
     * @param receiver The address that receives the exchange asset
     * @param owner The address whose receipts are burned, in case the caller is not the owner
     * @return shares (legacy name) — total amount of *exchange asset* transferred to `receiver`.
     *         For the `Input` flavor this is target-vault shares; for the `Output` flavor this is
     *         the target vault's underlying asset. The parameter is named `shares` for historical
     *         reasons and is not always denominated in vault shares.
     */
    function redeemExchangeAssetBatch(
        uint256[] calldata ids,
        uint256[] calldata amounts,
        address receiver,
        address owner
    ) external returns (uint256 shares);

    /// @notice Returns the id of the currently open round.
    /// @return The id of the currently open round.
    function getCurrentRound() external view returns (uint256);

    /**
     * @notice Returns the ERC-20 token paid out when exchanging a settled-round receipt.
     * @dev For `Input` vaults this is the target vault's share token; for `Output` vaults this is
     *      the target vault's underlying asset.
     * @return The address of the ERC-20 token used as the exchange asset.
     */
    function exchangeAsset() external view returns (address);

    /**
     * @notice Returns the per-round exchange rate snapshotted when the round was settled.
     * @dev The rate is stored as a `Price{ baseAmount, quoteAmount }` where `baseAmount` is the total
     *      exchange-asset amount produced by the settlement trade and `quoteAmount` is the total
     *      deposit-asset amount that was frozen for the round. `PriceUtils.quote(rate, amount)`
     *      converts a receipt amount into the matching exchange-asset amount. Returns a zero-valued
     *      `Price` for rounds that have not been settled yet.
     * @param round The round id to look up
     * @return The `Price{ baseAmount, quoteAmount }` snapshot for `round`, or a zero-valued `Price`
     *         if the round has not been settled.
     */
    function getExchangeRate(
        uint256 round
    ) external view returns (Price memory);

    /**
     * @notice Executes the settlement trade for a round that is currently in `InSettlement` and
     *         snapshots the per-round exchange rate from the actual trade result.
     * @dev Marks the round as `Settled` before calling `_operate`, so any reentrant attempt to
     *      re-settle the same round reverts on state. Restricted to the keeper role.
     * @param roundId The id of the round to be settled
     */
    function setRoundSettled(uint256 roundId) external;

    /**
     * @notice Batch variant of `setRoundSettled`. Settles several rounds in one keeper transaction.
     * @dev Each id must be in `InSettlement`. Restricted to the keeper role.
     * @param roundIds The ids of the rounds to be settled
     */
    function setRoundSettledBatch(uint256[] calldata roundIds) external;

    /// @notice Returns the minimum aggregate position size, in target-vault assets, that a user
    ///         must maintain to enter or exit. Returns 0 if the check is disabled.
    function minPositionSize() external view returns (uint256);

    /**
     * @notice Sets the minimum aggregate position size that a user must maintain to enter or exit.
     * @dev Setting `0` disables the check. The minimum is denominated in target-vault assets and is
     *      evaluated post-flight against the user's combined receipt + target-vault-share balance.
     *      Restricted to the governor role.
     * @param minSize The new minimum position size, or 0 to disable
     */
    function setMinPositionSize(uint256 minSize) external;

    /**
     * @notice Recovery path that moves a stuck `InSettlement` round back to `Opened` so users can
     *         redeem their receipts via the current-round path.
     * @dev Intended when `setRoundSettled` cannot proceed (e.g. underlying off-chain settlement
     *      failed). Pairs with `retryRound` when settlement becomes possible again. Reverts if the
     *      round is not in `InSettlement`. Restricted to the governor role.
     * @param roundId The id of the round to roll back
     */
    function emergencyRollbackRound(uint256 roundId) external;

    /**
     * @notice Pushes a past round in `Opened` state back to `InSettlement` so the keeper can attempt
     *         settlement again.
     * @dev Only valid for past rounds (`roundId < currentRound`) that are in `Opened` state. The
     *      typical recovery sequence is `emergencyRollbackRound` then `retryRound` then
     *      `setRoundSettled`. Reverts on the current round or on rounds in any other state.
     *      Restricted to the keeper role.
     * @param roundId The id of the round to retry
     */
    function retryRound(uint256 roundId) external;
}
