name: CI
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build and Unit Test
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Cache turbo build setup
        uses: actions/cache@v3
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.ref_name }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-turbo-${{ github.ref_name }}-
            ${{ runner.os }}-turbo-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 8.14.1

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Prebuild
        run: pnpm prebuild

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

      - name: Lint
        run: pnpm lint

      - name: Format
        run: pnpm format

      - name: Generate coverage report
        run: pnpm coverage:lcov
        working-directory: packages/core-contracts

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./packages/core-contracts/lcov.info
          flags: unittests
          name: codecov-umbrella

      # New step to update the README.md or any Markdown file with the dynamic badge
      - name: Update Markdown with Dynamic Codecov Badge
        run: |
          BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          BADGE_URL="https://codecov.io/gh/OasisDEX/summer-earn-protocol/branch/${BRANCH_NAME}/graph/badge.svg?token=${{ secrets.CODECOV_EMBED_TOKEN }}"
          sed -i "s|https://codecov.io/gh/OasisDEX/summer-earn-protocol/branch/main/graph/badge.svg|${BADGE_URL}|g" README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add README.md
          git commit -m "Update Codecov badge to current branch" -a || echo "No changes to commit"
          # Use GITHUB_HEAD_REF for PRs, GITHUB_REF for others
          BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          # Ensure we're pushing to a branch, not a detached HEAD
          git push origin HEAD:refs/heads/${BRANCH_NAME}
